// Command block-gen generates typed Rust block values from Dragonfly's block registry.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	_ "github.com/df-mc/dragonfly/server/block"
	"github.com/df-mc/dragonfly/server/world"
)

type blockState struct {
	name            string
	properties      map[string]any
	semanticDefault bool
}

type propertyKind uint8

const (
	propertyBool propertyKind = iota
	propertyUint8
	propertyInt32
	propertyString
)

const maxGeneratedNumericStateValues = 64

type propertySpec struct {
	name       string
	kind       propertyKind
	values     []any
	variable   bool
	enumName   string
	blockNames []string
}

type blockSpec struct {
	name               string
	typeName           string
	properties         []propertySpec
	semanticDefault    map[string]any
	hasSemanticDefault bool
}

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "fail if generated file is stale")
	flag.Parse()

	world.DefaultBlockRegistry.Finalize()
	blocks := world.DefaultBlockRegistry.Blocks()
	semanticDefaults := map[string]bool{}
	for _, block := range blocks {
		if state, ok := semanticZeroState(block); ok {
			semanticDefaults[blockStateKey(state)] = true
		}
	}
	states := make([]blockState, 0, len(blocks))
	for _, b := range blocks {
		name, properties := b.EncodeBlock()
		state := blockState{name: name, properties: properties}
		state.semanticDefault = semanticDefaults[blockStateKey(state)]
		states = append(states, state)
	}
	data, err := generate(states)
	if err != nil {
		fatal(err)
	}
	data, err = formatRust(data)
	if err != nil {
		fatal(err)
	}
	path := filepath.Join(*root, "rust", "dragonfly-plugin", "src", "blocks_generated.rs")
	if *check {
		current, err := os.ReadFile(path)
		if err != nil {
			fatal(err)
		}
		if !bytes.Equal(current, data) {
			fatal(fmt.Errorf("generated file is stale: %s", path))
		}
		return
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		fatal(err)
	}
}

func semanticZeroState(block world.Block) (state blockState, ok bool) {
	defer func() {
		if recover() != nil {
			state, ok = blockState{}, false
		}
	}()
	blockType := reflect.TypeOf(block)
	if blockType == nil {
		return blockState{}, false
	}
	zero := reflect.Zero(blockType)
	if blockType.Kind() == reflect.Pointer {
		zero = reflect.New(blockType.Elem())
	}
	value, ok := zero.Interface().(world.Block)
	if !ok {
		return blockState{}, false
	}
	name, properties := value.EncodeBlock()
	if name == "" {
		return blockState{}, false
	}
	return blockState{name: name, properties: properties, semanticDefault: true}, true
}

func blockStateKey(state blockState) string {
	names := make([]string, 0, len(state.properties))
	for name := range state.properties {
		names = append(names, name)
	}
	sort.Strings(names)
	var key strings.Builder
	key.WriteString(state.name)
	for _, name := range names {
		key.WriteByte(0)
		key.WriteString(name)
		key.WriteByte(0)
		key.WriteString(valueKey(state.properties[name]))
	}
	return key.String()
}

func formatRust(data []byte) ([]byte, error) {
	command := exec.Command("rustfmt", "--emit", "stdout", "--edition", "2024")
	command.Stdin = bytes.NewReader(data)
	output, err := command.Output()
	if err != nil {
		var exitError *exec.ExitError
		if errors.As(err, &exitError) {
			return nil, fmt.Errorf("rustfmt generated blocks: %s", strings.TrimSpace(string(exitError.Stderr)))
		}
		return nil, fmt.Errorf("rustfmt generated blocks: %w", err)
	}
	return output, nil
}

func generate(states []blockState) ([]byte, error) {
	blocks, err := inspect(states)
	if err != nil {
		return nil, err
	}
	assignEnumNames(blocks)

	var b strings.Builder
	b.WriteString("// Code generated by block-gen. DO NOT EDIT.\n\n")
	writtenEnums := map[string]bool{}
	for _, block := range blocks {
		for _, property := range block.properties {
			if !hasGeneratedStateType(property) || writtenEnums[property.enumName] {
				continue
			}
			writtenEnums[property.enumName] = true
			if property.kind == propertyString {
				writeStringEnum(&b, property)
			} else {
				writeNumericEnum(&b, property)
			}
		}
	}
	for _, block := range blocks {
		writeBlock(&b, block)
	}
	return []byte(b.String()), nil
}

func inspect(states []blockState) ([]blockSpec, error) {
	grouped := map[string][]blockState{}
	for _, state := range states {
		if state.name == "" {
			return nil, errors.New("block identifier must not be empty")
		}
		grouped[state.name] = append(grouped[state.name], state)
	}
	names := make([]string, 0, len(grouped))
	for name := range grouped {
		names = append(names, name)
	}
	sort.Strings(names)

	blocks := make([]blockSpec, 0, len(names))
	usedTypeNames := map[string]string{}
	for _, name := range names {
		typeName := rustTypeName(name)
		if previous, found := usedTypeNames[typeName]; found && previous != name {
			return nil, fmt.Errorf("block identifiers %q and %q both map to Rust type %s", previous, name, typeName)
		}
		usedTypeNames[typeName] = name
		properties, err := inspectProperties(name, grouped[name])
		if err != nil {
			return nil, err
		}
		var semanticDefault map[string]any
		hasSemanticDefault := false
		for _, state := range grouped[name] {
			if !state.semanticDefault {
				continue
			}
			if hasSemanticDefault {
				return nil, fmt.Errorf("block %q has more than one semantic default", name)
			}
			semanticDefault = state.properties
			hasSemanticDefault = true
		}
		blocks = append(blocks, blockSpec{
			name:               name,
			typeName:           typeName,
			properties:         properties,
			semanticDefault:    semanticDefault,
			hasSemanticDefault: hasSemanticDefault,
		})
	}
	return blocks, nil
}

func inspectProperties(blockName string, states []blockState) ([]propertySpec, error) {
	propertyNames := map[string]bool{}
	for _, state := range states {
		for name := range state.properties {
			propertyNames[name] = true
		}
	}
	names := make([]string, 0, len(propertyNames))
	for name := range propertyNames {
		names = append(names, name)
	}
	sort.Strings(names)

	properties := make([]propertySpec, 0, len(names))
	for _, name := range names {
		kinds := map[propertyKind]bool{}
		rawValues := make([]any, 0, len(states))
		for _, state := range states {
			value, found := state.properties[name]
			if !found {
				return nil, fmt.Errorf("block %q omits property %q in some states", blockName, name)
			}
			currentKind, err := kindOf(value)
			if err != nil {
				return nil, fmt.Errorf("block %q property %q: %w", blockName, name, err)
			}
			kinds[currentKind] = true
			rawValues = append(rawValues, value)
		}
		kind, normaliseBooleanByte, err := commonPropertyKind(kinds)
		if err != nil {
			return nil, fmt.Errorf("block %q has mixed property types for %q", blockName, name)
		}
		values := map[string]any{}
		for _, value := range rawValues {
			if normaliseBooleanByte {
				if boolean, ok := value.(bool); ok {
					value = uint8(0)
					if boolean {
						value = uint8(1)
					}
				}
			}
			values[valueKey(value)] = value
		}
		sortedValues := make([]any, 0, len(values))
		for _, value := range values {
			sortedValues = append(sortedValues, value)
		}
		sort.Slice(sortedValues, func(i, j int) bool { return valueKey(sortedValues[i]) < valueKey(sortedValues[j]) })
		properties = append(properties, propertySpec{
			name:     name,
			kind:     kind,
			values:   sortedValues,
			variable: len(sortedValues) > 1,
		})
	}
	return properties, nil
}

func commonPropertyKind(kinds map[propertyKind]bool) (kind propertyKind, normaliseBooleanByte bool, err error) {
	if len(kinds) == 1 {
		for kind := range kinds {
			return kind, false, nil
		}
	}
	if len(kinds) == 2 && kinds[propertyBool] && kinds[propertyUint8] {
		return propertyUint8, true, nil
	}
	return 0, false, errors.New("incompatible property kinds")
}

func kindOf(value any) (propertyKind, error) {
	switch value.(type) {
	case bool:
		return propertyBool, nil
	case uint8:
		return propertyUint8, nil
	case int32:
		return propertyInt32, nil
	case string:
		return propertyString, nil
	default:
		return 0, fmt.Errorf("unsupported property type %T", value)
	}
}

func valueKey(value any) string {
	switch value := value.(type) {
	case bool:
		return fmt.Sprintf("b:%t", value)
	case uint8:
		return fmt.Sprintf("u:%03d", value)
	case int32:
		return fmt.Sprintf("i:%011d", int64(value)+1<<31)
	case string:
		return "s:" + value
	default:
		panic(fmt.Sprintf("unsupported property type %T", value))
	}
}

func assignEnumNames(blocks []blockSpec) {
	type enumUse struct {
		blockIndex    int
		propertyIndex int
		signature     string
	}
	usesByProperty := map[string][]enumUse{}
	occupiedNames := map[string]bool{"Block": true, "Custom": true, "Property": true}
	for blockIndex := range blocks {
		occupiedNames[blocks[blockIndex].typeName] = true
		for propertyIndex, property := range blocks[blockIndex].properties {
			if !hasGeneratedStateType(property) {
				continue
			}
			values := make([]string, len(property.values))
			for i, value := range property.values {
				values[i] = valueKey(value)
			}
			usesByProperty[property.name] = append(usesByProperty[property.name], enumUse{
				blockIndex: blockIndex, propertyIndex: propertyIndex, signature: strings.Join(values, "\x00"),
			})
		}
	}
	propertyNames := make([]string, 0, len(usesByProperty))
	for propertyName := range usesByProperty {
		propertyNames = append(propertyNames, propertyName)
	}
	sort.Strings(propertyNames)
	assignedNames := map[string]string{}
	for _, propertyName := range propertyNames {
		uses := usesByProperty[propertyName]
		signatures := map[string]bool{}
		for _, use := range uses {
			signatures[use.signature] = true
		}
		for _, use := range uses {
			assignmentKey := propertyName + "\x00" + use.signature
			name := rustTypeIdentifier(rustPascal(propertyLocalName(propertyName)), "State")
			if len(signatures) > 1 {
				assignmentKey += "\x00" + blocks[use.blockIndex].typeName
				name = blocks[use.blockIndex].typeName + name
			}
			if assigned, found := assignedNames[assignmentKey]; found {
				name = assigned
			} else {
				base := name
				if occupiedNames[name] {
					name += "State"
				}
				for suffix := 2; occupiedNames[name]; suffix++ {
					name = fmt.Sprintf("%sState%d", base, suffix)
				}
				assignedNames[assignmentKey] = name
				occupiedNames[name] = true
			}
			blocks[use.blockIndex].properties[use.propertyIndex].enumName = name
		}
	}
}

func hasGeneratedStateType(property propertySpec) bool {
	if !property.variable {
		return false
	}
	if property.kind == propertyString {
		return true
	}
	return (property.kind == propertyInt32 || property.kind == propertyUint8) &&
		!isBinary(property.values) && len(property.values) <= maxGeneratedNumericStateValues
}

func writeStringEnum(b *strings.Builder, property propertySpec) {
	fmt.Fprintf(b, "#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\npub enum %s {\n", property.enumName)
	for _, value := range property.values {
		fmt.Fprintf(b, "    %s,\n", rustVariant(value.(string)))
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "impl %s {\n    pub const fn as_str(self) -> &'static str {\n        match self {\n", property.enumName)
	for _, value := range property.values {
		fmt.Fprintf(b, "            Self::%s => %s,\n", rustVariant(value.(string)), strconv.Quote(value.(string)))
	}
	b.WriteString("        }\n    }\n}\n\n")
}

func writeNumericEnum(b *strings.Builder, property propertySpec) {
	representation, accessor := "i32", "as_i32"
	if property.kind == propertyUint8 {
		representation, accessor = "u8", "as_u8"
	}
	fmt.Fprintf(b, "#[repr(%s)]\n#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\npub enum %s {\n", representation, property.enumName)
	for _, value := range property.values {
		fmt.Fprintf(b, "    %s = %v,\n", rustNumericVariant(value), value)
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(b, "impl %s {\n    pub const fn %s(self) -> %s { self as %s }\n}\n\n", property.enumName, accessor, representation, representation)
}

func writeBlock(b *strings.Builder, block blockSpec) {
	variables := make([]propertySpec, 0, len(block.properties))
	for _, property := range block.properties {
		if property.variable {
			variables = append(variables, property)
		}
	}
	if len(variables) == 0 {
		fmt.Fprintf(b, "#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]\npub struct %s;\n\n", block.typeName)
	} else {
		fmt.Fprintf(b, "#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]\npub struct %s {\n", block.typeName)
		for _, property := range variables {
			fmt.Fprintf(b, "    %s: %s,\n", rustFieldName(property.name), rustPropertyType(property))
		}
		b.WriteString("}\n\n")
		fmt.Fprintf(b, "impl %s {\n", block.typeName)
		if block.hasSemanticDefault {
			b.WriteString("    pub const DEFAULT: Self = Self { ")
			for i, property := range variables {
				if i != 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(b, "%s: %s", rustFieldName(property.name), rustDefaultValue(property, block.semanticDefault[property.name]))
			}
			b.WriteString(" };\n\n")
		}
		b.WriteString("    pub const fn new(")
		if len(variables) <= 2 || !block.hasSemanticDefault {
			for i, property := range variables {
				if i != 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(b, "%s: %s", rustFieldName(property.name), rustPropertyType(property))
			}
			b.WriteString(") -> Self { Self { ")
			for i, property := range variables {
				if i != 0 {
					b.WriteString(", ")
				}
				b.WriteString(rustFieldName(property.name))
			}
			b.WriteString(" } }\n")
		} else {
			b.WriteString(") -> Self { Self::DEFAULT }\n")
		}
		for _, property := range variables {
			field := rustFieldName(property.name)
			fmt.Fprintf(b, "\n    pub const fn with_%s(mut self, %s: %s) -> Self { self.%s = %s; self }\n", rustMethodName(property.name), field, rustPropertyType(property), field, field)
		}
		b.WriteString("}\n\n")
		if block.hasSemanticDefault {
			fmt.Fprintf(b, "impl Default for %s {\n    fn default() -> Self { Self::DEFAULT }\n}\n\n", block.typeName)
		}
	}

	argument := "value"
	if len(variables) == 0 {
		argument = "_value"
	}
	fmt.Fprintf(b, "impl From<%s> for Block {\n    fn from(%s: %s) -> Self {\n", block.typeName, argument, block.typeName)
	if len(block.properties) == 0 {
		fmt.Fprintf(b, "        Block::from_properties(%s, [])\n", strconv.Quote(block.name))
	} else {
		fmt.Fprintf(b, "        Block::from_properties(%s, [\n", strconv.Quote(block.name))
		for _, property := range block.properties {
			fmt.Fprintf(b, "            (%s, %s),\n", strconv.Quote(property.name), rustPropertyValue(property))
		}
		b.WriteString("        ])\n")
	}
	b.WriteString("    }\n}\n\n")
}

func rustDefaultValue(property propertySpec, value any) string {
	switch property.kind {
	case propertyBool:
		return fmt.Sprintf("%t", value.(bool))
	case propertyUint8:
		byteValue, ok := value.(uint8)
		if !ok {
			if boolean := value.(bool); boolean {
				byteValue = 1
			}
		}
		if isBinary(property.values) {
			return fmt.Sprintf("%t", byteValue != 0)
		}
		if hasGeneratedStateType(property) {
			return property.enumName + "::" + rustNumericVariant(byteValue)
		}
		return fmt.Sprintf("%d", byteValue)
	case propertyInt32:
		if hasGeneratedStateType(property) {
			return property.enumName + "::" + rustNumericVariant(value)
		}
		return fmt.Sprintf("%d", value.(int32))
	case propertyString:
		return property.enumName + "::" + rustVariant(value.(string))
	default:
		panic("invalid property kind")
	}
}

func rustPropertyType(property propertySpec) string {
	switch property.kind {
	case propertyBool:
		return "bool"
	case propertyUint8:
		if isBinary(property.values) {
			return "bool"
		}
		if hasGeneratedStateType(property) {
			return property.enumName
		}
		return "u8"
	case propertyInt32:
		if hasGeneratedStateType(property) {
			return property.enumName
		}
		return "i32"
	case propertyString:
		return property.enumName
	default:
		panic("invalid property kind")
	}
}

func rustPropertyValue(property propertySpec) string {
	if !property.variable {
		return rustConstantProperty(property.values[0])
	}
	field := "value." + rustFieldName(property.name)
	switch property.kind {
	case propertyBool:
		return "Property::Bool(" + field + ")"
	case propertyUint8:
		if isBinary(property.values) {
			return "Property::Uint8(u8::from(" + field + "))"
		}
		if hasGeneratedStateType(property) {
			return "Property::Uint8(" + field + ".as_u8())"
		}
		return "Property::Uint8(" + field + ")"
	case propertyInt32:
		if hasGeneratedStateType(property) {
			return "Property::Int32(" + field + ".as_i32())"
		}
		return "Property::Int32(" + field + ")"
	case propertyString:
		return "Property::String(" + field + ".as_str().to_owned())"
	default:
		panic("invalid property kind")
	}
}

func rustNumericVariant(value any) string {
	var number int64
	switch value := value.(type) {
	case uint8:
		number = int64(value)
	case int32:
		number = int64(value)
	default:
		panic(fmt.Sprintf("unsupported numeric property type %T", value))
	}
	if number < 0 {
		return fmt.Sprintf("ValueNegative%d", -number)
	}
	return fmt.Sprintf("Value%d", number)
}

func rustConstantProperty(value any) string {
	switch value := value.(type) {
	case bool:
		return fmt.Sprintf("Property::Bool(%t)", value)
	case uint8:
		return fmt.Sprintf("Property::Uint8(%d)", value)
	case int32:
		return fmt.Sprintf("Property::Int32(%d)", value)
	case string:
		return fmt.Sprintf("Property::String(%s.to_owned())", strconv.Quote(value))
	default:
		panic(fmt.Sprintf("unsupported property type %T", value))
	}
}

func isBinary(values []any) bool {
	if len(values) != 2 {
		return false
	}
	zero, zeroOK := values[0].(uint8)
	one, oneOK := values[1].(uint8)
	return zeroOK && oneOK && zero == 0 && one == 1
}

func rustTypeName(identifier string) string {
	namespace, name, found := strings.Cut(identifier, ":")
	if !found {
		return rustTypeIdentifier(rustPascal(identifier), "Block")
	}
	if namespace == "minecraft" {
		return rustTypeIdentifier(rustPascal(name), "Block")
	}
	return rustTypeIdentifier(rustPascal(namespace)+rustPascal(name), "Block")
}

func rustTypeIdentifier(name, prefix string) string {
	first, _ := utf8.DecodeRuneInString(name)
	if unicode.IsDigit(first) || name == "Self" {
		return prefix + name
	}
	if name == "Block" || name == "Custom" || name == "Property" {
		return "Builtin" + name
	}
	return name
}

func rustPascal(value string) string {
	var b strings.Builder
	upper := true
	for _, r := range value {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			upper = true
			continue
		}
		if upper {
			r = unicode.ToUpper(r)
			upper = false
		}
		b.WriteRune(r)
	}
	if b.Len() == 0 {
		return "Block"
	}
	return b.String()
}

func rustVariant(value string) string {
	name := rustPascal(value)
	if unicode.IsDigit([]rune(name)[0]) {
		return "Value" + name
	}
	if name == "Self" || name == "Super" || name == "Crate" {
		return name + "Value"
	}
	return name
}

func rustFieldName(value string) string {
	value = propertyLocalName(value)
	var b strings.Builder
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	value = b.String()
	first, _ := utf8.DecodeRuneInString(value)
	if unicode.IsDigit(first) || value == "self" || value == "Self" || value == "super" || value == "crate" {
		return "state_" + value
	}
	switch value {
	case "as", "break", "const", "continue", "else", "enum", "extern", "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod", "move", "mut", "pub", "ref", "return", "static", "struct", "trait", "true", "type", "unsafe", "use", "where", "while", "async", "await", "dyn":
		return "r#" + value
	default:
		return value
	}
}

func rustMethodName(value string) string {
	value = propertyLocalName(value)
	var b strings.Builder
	for _, r := range value {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			b.WriteRune(r)
		} else {
			b.WriteByte('_')
		}
	}
	return b.String()
}

func propertyLocalName(value string) string {
	if _, local, found := strings.Cut(value, ":"); found {
		return local
	}
	return value
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
