// Code generated by abi-gen v1. DO NOT EDIT.

use core::ffi::c_void;

pub const DF_ABI_VERSION: u32 = 1;
pub const DF_STATUS_OK: DfStatus = 0;
pub const DF_STATUS_ERROR: DfStatus = 1;
pub type DfStatus = i32;
pub type DfEventId = u32;

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerId { pub bytes: [u8; 16], pub generation: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfVec3 { pub x: f64, pub y: f64, pub z: f64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfRotation { pub yaw: f32, pub pitch: f32 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfStringView { pub data: *const u8, pub len: u64 }
impl Default for DfStringView {
    fn default() -> Self { Self { data: core::ptr::null(), len: 0 } }
}
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfStringBuffer { pub data: *mut u8, pub len: u64, pub capacity: u64 }
impl Default for DfStringBuffer {
    fn default() -> Self { Self { data: core::ptr::null_mut(), len: 0, capacity: 0 } }
}
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandParameter { pub kind: u32, pub name: DfStringView, pub values: *const DfStringView, pub value_count: u64 }
pub const DF_COMMAND_PARAMETER_SUBCOMMAND: u32 = 1;
pub const DF_COMMAND_PARAMETER_ENUM: u32 = 2;
pub const DF_COMMAND_PARAMETER_STRING: u32 = 3;
pub const DF_COMMAND_PARAMETER_INTEGER: u32 = 4;
pub const DF_COMMAND_PARAMETER_FLOAT: u32 = 5;
pub const DF_COMMAND_PARAMETER_BOOL: u32 = 6;
pub const DF_COMMAND_PARAMETER_DYNAMIC_ENUM: u32 = 7;
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandOverload { pub parameters: *const DfCommandParameter, pub parameter_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandDescriptor { pub name: DfStringView, pub description: DfStringView, pub overloads: *const DfCommandOverload, pub overload_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandInput { pub source: DfStringView, pub arguments: DfStringView }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandState { pub failed: u8, pub output: DfStringBuffer }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfAbiHeader { pub abi_version: u32, pub struct_size: u32, pub subscriptions: u64 }

pub const DF_EVENT_PLAYER_MOVE: DfEventId = 1;
pub const DF_SUBSCRIPTION_PLAYER_MOVE: u64 = 1u64 << 0;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerMoveInput {
    pub player: DfPlayerId,
    pub old_position: DfVec3,
    pub new_position: DfVec3,
    pub rotation: DfRotation,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerMoveState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_CHAT: DfEventId = 2;
pub const DF_SUBSCRIPTION_PLAYER_CHAT: u64 = 1u64 << 1;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerChatInput {
    pub player: DfPlayerId,
    pub message: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerChatState {
    pub cancelled: u8,
    pub has_replacement: u8,
    pub replacement: DfStringBuffer,
}

pub type DfPluginCreateFn = unsafe extern "C" fn() -> *mut c_void;
pub type DfPluginLifecycleFn = unsafe extern "C" fn(instance: *mut c_void) -> DfStatus;
pub type DfPluginCommandsFn = unsafe extern "C" fn(instance: *mut c_void, count: *mut u64) -> *const DfCommandDescriptor;
pub type DfHandleCommandFn = unsafe extern "C" fn(instance: *mut c_void, command: u64, input: *const DfCommandInput, state: *mut DfCommandState) -> DfStatus;
pub type DfCommandEnumOptionsFn = unsafe extern "C" fn(instance: *mut c_void, command: u64, overload: u64, parameter: u64, source: DfStringView, output: *mut DfStringBuffer) -> DfStatus;
pub type DfPluginDestroyFn = unsafe extern "C" fn(instance: *mut c_void);
pub type DfHandleEventFn = unsafe extern "C" fn(instance: *mut c_void, event_id: DfEventId, input: *const c_void, state: *mut c_void) -> DfStatus;

#[repr(C)]
pub struct DfPluginApiV1 {
    pub header: DfAbiHeader,
    pub plugin_id: DfStringView,
    pub create: Option<DfPluginCreateFn>,
    pub enable: Option<DfPluginLifecycleFn>,
    pub disable: Option<DfPluginLifecycleFn>,
    pub commands: Option<DfPluginCommandsFn>,
    pub handle_command: Option<DfHandleCommandFn>,
    pub command_enum_options: Option<DfCommandEnumOptionsFn>,
    pub destroy: Option<DfPluginDestroyFn>,
    pub handle_event: Option<DfHandleEventFn>,
}

pub type DfPluginEntryV1Fn = unsafe extern "C" fn() -> *const DfPluginApiV1;

unsafe impl Sync for DfPluginApiV1 {}
