// Code generated by abi-gen v1. DO NOT EDIT.

use core::ffi::c_void;

pub const DF_ABI_VERSION: u32 = 1;
pub const DF_STATUS_OK: DfStatus = 0;
pub const DF_STATUS_ERROR: DfStatus = 1;
pub type DfStatus = i32;
pub type DfEventId = u32;

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerId { pub bytes: [u8; 16], pub generation: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfVec3 { pub x: f64, pub y: f64, pub z: f64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfRotation { pub yaw: f32, pub pitch: f32 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfBlockPos { pub x: i32, pub y: i32, pub z: i32 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfStringView { pub data: *const u8, pub len: u64 }
impl Default for DfStringView {
    fn default() -> Self { Self { data: core::ptr::null(), len: 0 } }
}
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfStringBuffer { pub data: *mut u8, pub len: u64, pub capacity: u64 }
impl Default for DfStringBuffer {
    fn default() -> Self { Self { data: core::ptr::null_mut(), len: 0, capacity: 0 } }
}
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandParameter { pub kind: u32, pub optional: u8, pub name: DfStringView, pub values: *const DfStringView, pub value_count: u64 }
pub const DF_COMMAND_PARAMETER_SUBCOMMAND: u32 = 1;
pub const DF_COMMAND_PARAMETER_ENUM: u32 = 2;
pub const DF_COMMAND_PARAMETER_STRING: u32 = 3;
pub const DF_COMMAND_PARAMETER_INTEGER: u32 = 4;
pub const DF_COMMAND_PARAMETER_FLOAT: u32 = 5;
pub const DF_COMMAND_PARAMETER_BOOL: u32 = 6;
pub const DF_COMMAND_PARAMETER_DYNAMIC_ENUM: u32 = 7;
pub const DF_COMMAND_PARAMETER_PLAYER: u32 = 8;
pub const DF_COMMAND_PARAMETER_RAW_TEXT: u32 = 9;
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandOverload { pub parameters: *const DfCommandParameter, pub parameter_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandDescriptor { pub name: DfStringView, pub description: DfStringView, pub overloads: *const DfCommandOverload, pub overload_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandEnumContext { pub source: DfStringView, pub online_players: *const DfStringView, pub online_player_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandPlayer { pub player: DfPlayerId, pub name: DfStringView, pub latency_milliseconds: u64 }
pub const DF_COMMAND_SOURCE_UNKNOWN: u32 = 0;
pub const DF_COMMAND_SOURCE_PLAYER: u32 = 1;
pub const DF_COMMAND_SOURCE_CONSOLE: u32 = 2;
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandInput { pub source: DfStringView, pub arguments: DfStringView, pub source_kind: u32, pub source_player: DfPlayerId, pub online_players: *const DfCommandPlayer, pub online_player_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandState { pub failed: u8, pub output: DfStringBuffer }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfAbiHeader { pub abi_version: u32, pub struct_size: u32, pub subscriptions: u64 }

pub const DF_EVENT_PLAYER_MOVE: DfEventId = 1;
pub const DF_SUBSCRIPTION_PLAYER_MOVE: u64 = 1u64 << 0;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerMoveInput {
    pub player: DfPlayerId,
    pub old_position: DfVec3,
    pub new_position: DfVec3,
    pub rotation: DfRotation,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerMoveState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_CHAT: DfEventId = 2;
pub const DF_SUBSCRIPTION_PLAYER_CHAT: u64 = 1u64 << 1;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerChatInput {
    pub player: DfPlayerId,
    pub message: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerChatState {
    pub cancelled: u8,
    pub has_replacement: u8,
    pub replacement: DfStringBuffer,
}

pub const DF_EVENT_PLAYER_JOIN: DfEventId = 3;
pub const DF_SUBSCRIPTION_PLAYER_JOIN: u64 = 1u64 << 2;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerJoinInput {
    pub player: DfPlayerId,
    pub name: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerJoinState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_QUIT: DfEventId = 4;
pub const DF_SUBSCRIPTION_PLAYER_QUIT: u64 = 1u64 << 3;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerQuitInput {
    pub player: DfPlayerId,
    pub name: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerQuitState {
    pub _reserved: u8,
}

pub const DF_EVENT_PLAYER_HURT: DfEventId = 5;
pub const DF_SUBSCRIPTION_PLAYER_HURT: u64 = 1u64 << 4;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerHurtInput {
    pub player: DfPlayerId,
    pub immune: u8,
    pub source: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerHurtState {
    pub cancelled: u8,
    pub damage: f64,
    pub attack_immunity_milliseconds: u64,
}

pub const DF_EVENT_PLAYER_HEAL: DfEventId = 6;
pub const DF_SUBSCRIPTION_PLAYER_HEAL: u64 = 1u64 << 5;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerHealInput {
    pub player: DfPlayerId,
    pub source: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerHealState {
    pub cancelled: u8,
    pub health: f64,
}

pub const DF_EVENT_PLAYER_BLOCK_BREAK: DfEventId = 7;
pub const DF_SUBSCRIPTION_PLAYER_BLOCK_BREAK: u64 = 1u64 << 6;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerBlockBreakInput {
    pub player: DfPlayerId,
    pub position: DfBlockPos,
    pub block: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerBlockBreakState {
    pub cancelled: u8,
    pub experience: i32,
}

pub const DF_EVENT_PLAYER_BLOCK_PLACE: DfEventId = 8;
pub const DF_SUBSCRIPTION_PLAYER_BLOCK_PLACE: u64 = 1u64 << 7;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerBlockPlaceInput {
    pub player: DfPlayerId,
    pub position: DfBlockPos,
    pub block: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerBlockPlaceState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_FOOD_LOSS: DfEventId = 9;
pub const DF_SUBSCRIPTION_PLAYER_FOOD_LOSS: u64 = 1u64 << 8;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerFoodLossInput {
    pub player: DfPlayerId,
    pub from: i32,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerFoodLossState {
    pub cancelled: u8,
    pub to: i32,
}

pub const DF_EVENT_PLAYER_DEATH: DfEventId = 10;
pub const DF_SUBSCRIPTION_PLAYER_DEATH: u64 = 1u64 << 9;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerDeathInput {
    pub player: DfPlayerId,
    pub source: DfStringView,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerDeathState {
    pub keep_inventory: u8,
}

pub const DF_EVENT_PLAYER_START_BREAK: DfEventId = 11;
pub const DF_SUBSCRIPTION_PLAYER_START_BREAK: u64 = 1u64 << 10;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerStartBreakInput {
    pub player: DfPlayerId,
    pub position: DfBlockPos,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerStartBreakState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_FIRE_EXTINGUISH: DfEventId = 12;
pub const DF_SUBSCRIPTION_PLAYER_FIRE_EXTINGUISH: u64 = 1u64 << 11;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerFireExtinguishInput {
    pub player: DfPlayerId,
    pub position: DfBlockPos,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerFireExtinguishState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_TOGGLE_SPRINT: DfEventId = 13;
pub const DF_SUBSCRIPTION_PLAYER_TOGGLE_SPRINT: u64 = 1u64 << 12;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerToggleSprintInput {
    pub player: DfPlayerId,
    pub after: u8,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerToggleSprintState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_TOGGLE_SNEAK: DfEventId = 14;
pub const DF_SUBSCRIPTION_PLAYER_TOGGLE_SNEAK: u64 = 1u64 << 13;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerToggleSneakInput {
    pub player: DfPlayerId,
    pub after: u8,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerToggleSneakState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_JUMP: DfEventId = 15;
pub const DF_SUBSCRIPTION_PLAYER_JUMP: u64 = 1u64 << 14;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerJumpInput {
    pub player: DfPlayerId,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerJumpState {
    pub _reserved: u8,
}

pub const DF_EVENT_PLAYER_TELEPORT: DfEventId = 16;
pub const DF_SUBSCRIPTION_PLAYER_TELEPORT: u64 = 1u64 << 15;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerTeleportInput {
    pub player: DfPlayerId,
    pub position: DfVec3,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerTeleportState {
    pub cancelled: u8,
}

pub const DF_EVENT_PLAYER_EXPERIENCE_GAIN: DfEventId = 17;
pub const DF_SUBSCRIPTION_PLAYER_EXPERIENCE_GAIN: u64 = 1u64 << 16;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerExperienceGainInput {
    pub player: DfPlayerId,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerExperienceGainState {
    pub cancelled: u8,
    pub amount: i32,
}

pub const DF_EVENT_PLAYER_PUNCH_AIR: DfEventId = 18;
pub const DF_SUBSCRIPTION_PLAYER_PUNCH_AIR: u64 = 1u64 << 17;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerPunchAirInput {
    pub player: DfPlayerId,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerPunchAirState {
    pub cancelled: u8,
}

pub type DfPluginCreateFn = unsafe extern "C" fn() -> *mut c_void;
pub type DfPluginLifecycleFn = unsafe extern "C" fn(instance: *mut c_void) -> DfStatus;
pub type DfPluginCommandsFn = unsafe extern "C" fn(instance: *mut c_void, count: *mut u64) -> *const DfCommandDescriptor;
pub type DfHandleCommandFn = unsafe extern "C" fn(instance: *mut c_void, command: u64, input: *const DfCommandInput, state: *mut DfCommandState) -> DfStatus;
pub type DfCommandEnumOptionsFn = unsafe extern "C" fn(instance: *mut c_void, command: u64, overload: u64, parameter: u64, context: *const DfCommandEnumContext, output: *mut DfStringBuffer) -> DfStatus;
pub type DfPluginDestroyFn = unsafe extern "C" fn(instance: *mut c_void);
pub type DfHandleEventFn = unsafe extern "C" fn(instance: *mut c_void, event_id: DfEventId, input: *const c_void, state: *mut c_void) -> DfStatus;

#[repr(C)]
pub struct DfPluginApiV1 {
    pub header: DfAbiHeader,
    pub plugin_id: DfStringView,
    pub create: Option<DfPluginCreateFn>,
    pub enable: Option<DfPluginLifecycleFn>,
    pub disable: Option<DfPluginLifecycleFn>,
    pub commands: Option<DfPluginCommandsFn>,
    pub handle_command: Option<DfHandleCommandFn>,
    pub command_enum_options: Option<DfCommandEnumOptionsFn>,
    pub destroy: Option<DfPluginDestroyFn>,
    pub handle_event: Option<DfHandleEventFn>,
}

pub type DfPluginEntryV1Fn = unsafe extern "C" fn() -> *const DfPluginApiV1;

unsafe impl Sync for DfPluginApiV1 {}
