[plugins]
  directory = "plugins"

[worlds]
  directory = ".data/worlds"

[dragonfly]

  [dragonfly.Network]
    Address = ":19132"

  [dragonfly.Server]
    Name = "Minimal Bedrock Gophers"
    AuthEnabled = false

  [dragonfly.World]
    SaveData = true
    Folder = ".data/world"

  [dragonfly.Players]
    MaximumChunkRadius = 12
    SaveData = true
    Folder = ".data/players"

  [dragonfly.Resources]
    AutoBuildPack = true
    Folder = ".data/resources"
