// Code generated by abi-gen v1. DO NOT EDIT.

package native

import "time"

type PlayerStateKind uint32

const (
	PlayerStateGameMode           PlayerStateKind = 0
	PlayerStateHeal               PlayerStateKind = 1
	PlayerStateHurt               PlayerStateKind = 2
	PlayerStateFood               PlayerStateKind = 3
	PlayerStateMaxHealth          PlayerStateKind = 4
	PlayerStateHealth             PlayerStateKind = 5
	PlayerStateExperienceLevel    PlayerStateKind = 6
	PlayerStateExperienceProgress PlayerStateKind = 7
	PlayerStateScale              PlayerStateKind = 8
	PlayerStateInvisible          PlayerStateKind = 9
	PlayerStateImmobile           PlayerStateKind = 10
)

type PlayerStateValue struct {
	Number  float64
	Integer int64
}

type EffectType uint32

const (
	EffectSpeed          EffectType = 1
	EffectSlowness       EffectType = 2
	EffectHaste          EffectType = 3
	EffectMiningFatigue  EffectType = 4
	EffectStrength       EffectType = 5
	EffectInstantHealth  EffectType = 6
	EffectInstantDamage  EffectType = 7
	EffectJumpBoost      EffectType = 8
	EffectNausea         EffectType = 9
	EffectRegeneration   EffectType = 10
	EffectResistance     EffectType = 11
	EffectFireResistance EffectType = 12
	EffectWaterBreathing EffectType = 13
	EffectInvisibility   EffectType = 14
	EffectBlindness      EffectType = 15
	EffectNightVision    EffectType = 16
	EffectHunger         EffectType = 17
	EffectWeakness       EffectType = 18
	EffectPoison         EffectType = 19
	EffectWither         EffectType = 20
	EffectHealthBoost    EffectType = 21
	EffectAbsorption     EffectType = 22
	EffectSaturation     EffectType = 23
	EffectLevitation     EffectType = 24
	EffectFatalPoison    EffectType = 25
	EffectConduitPower   EffectType = 26
	EffectSlowFalling    EffectType = 27
	EffectDarkness       EffectType = 30
)

type PlayerEffectOperation uint32

const (
	PlayerEffectAdd PlayerEffectOperation = iota
	PlayerEffectRemove
)

type PlayerEffect struct {
	Type            EffectType
	Level           int32
	Duration        time.Duration
	Ambient         bool
	Infinite        bool
	ParticlesHidden bool
}

type PlayerTextKind uint32

const (
	PlayerTextMessage      PlayerTextKind = 0
	PlayerTextTip          PlayerTextKind = 1
	PlayerTextPopup        PlayerTextKind = 2
	PlayerTextJukeboxPopup PlayerTextKind = 3
	PlayerTextNameTag      PlayerTextKind = 4
)
