/* Code generated by abi-gen v1. DO NOT EDIT. */
#ifndef BEDROCK_GOPHERS_PLAYER_OPERATIONS_GENERATED_H
#define BEDROCK_GOPHERS_PLAYER_OPERATIONS_GENERATED_H

#if UINTPTR_MAX == UINT64_MAX
_Static_assert(offsetof(DfHostApiV21, player_experience_set) == 488, "DfHostApiV21.player_experience_set ABI offset changed");
#endif

extern DfStatus bg_go_player_experience_set(uint64_t context, DfInvocationId invocation, DfPlayerId player, int32_t level, double progress);
static DfStatus host_player_experience_set(uint64_t context, DfInvocationId invocation, DfPlayerId player, int32_t level, double progress) {
    return bg_go_player_experience_set(context, invocation, player, level, progress);
}

#define BG_PLAYER_OPERATION_HOST_FIELDS \
    .player_experience_set = host_player_experience_set,

#endif
