// Code generated by abi-gen v1. DO NOT EDIT.

package native

import "time"

type PlayerStateKind uint32

const (
	PlayerStateGameMode           PlayerStateKind = 0
	PlayerStateHeal               PlayerStateKind = 1
	PlayerStateHurt               PlayerStateKind = 2
	PlayerStateFood               PlayerStateKind = 3
	PlayerStateMaxHealth          PlayerStateKind = 4
	PlayerStateHealth             PlayerStateKind = 5
	PlayerStateExperienceLevel    PlayerStateKind = 6
	PlayerStateExperienceProgress PlayerStateKind = 7
	PlayerStateScale              PlayerStateKind = 8
	PlayerStateInvisible          PlayerStateKind = 9
	PlayerStateImmobile           PlayerStateKind = 10
	PlayerStateSound              PlayerStateKind = 11
)

type PlayerStateValue struct {
	Number  float64
	Integer int64
}

type EffectType uint32

const (
	EffectSpeed          EffectType = 1
	EffectSlowness       EffectType = 2
	EffectHaste          EffectType = 3
	EffectMiningFatigue  EffectType = 4
	EffectStrength       EffectType = 5
	EffectInstantHealth  EffectType = 6
	EffectInstantDamage  EffectType = 7
	EffectJumpBoost      EffectType = 8
	EffectNausea         EffectType = 9
	EffectRegeneration   EffectType = 10
	EffectResistance     EffectType = 11
	EffectFireResistance EffectType = 12
	EffectWaterBreathing EffectType = 13
	EffectInvisibility   EffectType = 14
	EffectBlindness      EffectType = 15
	EffectNightVision    EffectType = 16
	EffectHunger         EffectType = 17
	EffectWeakness       EffectType = 18
	EffectPoison         EffectType = 19
	EffectWither         EffectType = 20
	EffectHealthBoost    EffectType = 21
	EffectAbsorption     EffectType = 22
	EffectSaturation     EffectType = 23
	EffectLevitation     EffectType = 24
	EffectFatalPoison    EffectType = 25
	EffectConduitPower   EffectType = 26
	EffectSlowFalling    EffectType = 27
	EffectDarkness       EffectType = 30
)

type PlayerEffectOperation uint32

const (
	PlayerEffectAdd PlayerEffectOperation = iota
	PlayerEffectRemove
)

type PlayerEffect struct {
	Type            EffectType
	Level           int32
	Duration        time.Duration
	Ambient         bool
	Infinite        bool
	ParticlesHidden bool
}

type PlayerTextKind uint32

const (
	PlayerTextMessage      PlayerTextKind = 0
	PlayerTextTip          PlayerTextKind = 1
	PlayerTextPopup        PlayerTextKind = 2
	PlayerTextJukeboxPopup PlayerTextKind = 3
	PlayerTextNameTag      PlayerTextKind = 4
	PlayerTextDisconnect   PlayerTextKind = 5
	PlayerTextKick         PlayerTextKind = 6
)

type SoundType uint32

const (
	SoundAnvilBreak                 SoundType = 0
	SoundAnvilLand                  SoundType = 1
	SoundAnvilUse                   SoundType = 2
	SoundArrowHit                   SoundType = 3
	SoundBarrelClose                SoundType = 4
	SoundBarrelOpen                 SoundType = 5
	SoundBlastFurnaceCrackle        SoundType = 6
	SoundBowShoot                   SoundType = 7
	SoundBurning                    SoundType = 8
	SoundBurp                       SoundType = 9
	SoundCampfireCrackle            SoundType = 10
	SoundChestClose                 SoundType = 11
	SoundChestOpen                  SoundType = 12
	SoundClick                      SoundType = 13
	SoundComposterEmpty             SoundType = 14
	SoundComposterFill              SoundType = 15
	SoundComposterFillLayer         SoundType = 16
	SoundComposterReady             SoundType = 17
	SoundCopperScraped              SoundType = 18
	SoundCrossbowShoot              SoundType = 19
	SoundDecoratedPotInsertFailed   SoundType = 20
	SoundDeny                       SoundType = 21
	SoundDoorCrash                  SoundType = 22
	SoundDrowning                   SoundType = 23
	SoundEnderChestClose            SoundType = 24
	SoundEnderChestOpen             SoundType = 25
	SoundExperience                 SoundType = 26
	SoundExplosion                  SoundType = 27
	SoundFireCharge                 SoundType = 28
	SoundFireExtinguish             SoundType = 29
	SoundFireworkBlast              SoundType = 30
	SoundFireworkHugeBlast          SoundType = 31
	SoundFireworkLaunch             SoundType = 32
	SoundFireworkTwinkle            SoundType = 33
	SoundFizz                       SoundType = 34
	SoundFurnaceCrackle             SoundType = 35
	SoundGhastShoot                 SoundType = 36
	SoundGhastWarning               SoundType = 37
	SoundGlassBreak                 SoundType = 38
	SoundIgnite                     SoundType = 39
	SoundItemAdd                    SoundType = 40
	SoundItemBreak                  SoundType = 41
	SoundItemFrameRemove            SoundType = 42
	SoundItemFrameRotate            SoundType = 43
	SoundItemThrow                  SoundType = 44
	SoundLecternBookPlace           SoundType = 45
	SoundLevelUp                    SoundType = 46
	SoundLightningExplode           SoundType = 47
	SoundLightningThunder           SoundType = 48
	SoundMusicDiscEnd               SoundType = 49
	SoundPop                        SoundType = 50
	SoundPotionBrewed               SoundType = 51
	SoundPowerOff                   SoundType = 52
	SoundPowerOn                    SoundType = 53
	SoundSignWaxed                  SoundType = 54
	SoundSmokerCrackle              SoundType = 55
	SoundStopUsingSpyglass          SoundType = 56
	SoundTnt                        SoundType = 57
	SoundTeleport                   SoundType = 58
	SoundThunder                    SoundType = 59
	SoundTotem                      SoundType = 60
	SoundUseSpyglass                SoundType = 61
	SoundWaxRemoved                 SoundType = 62
	SoundWaxedSignFailedInteraction SoundType = 63
)
