/* Code generated by abi-gen v1. DO NOT EDIT. */
#ifndef BEDROCK_GOPHERS_DRAGONFLY_PLUGIN_H
#define BEDROCK_GOPHERS_DRAGONFLY_PLUGIN_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DF_ABI_VERSION 1u
#define DF_STATUS_OK 0
#define DF_STATUS_ERROR 1

typedef int32_t DfStatus;
typedef uint32_t DfEventId;

typedef struct { uint8_t bytes[16]; uint64_t generation; } DfPlayerId;
typedef struct { double x; double y; double z; } DfVec3;
typedef struct { double yaw; double pitch; } DfRotation;
typedef struct { int32_t x; int32_t y; int32_t z; } DfBlockPos;
typedef struct { const uint8_t *data; uint64_t len; } DfStringView;
typedef struct { uint8_t *data; uint64_t len; uint64_t capacity; } DfStringBuffer;
typedef struct { DfStringView identifier; int32_t metadata; int32_t count; int32_t damage; } DfItemStackView;
#define DF_PLAYER_TRANSFORM_TELEPORT 0u
#define DF_PLAYER_TRANSFORM_MOVE 1u
#define DF_PLAYER_TRANSFORM_VELOCITY 2u
#define DF_PLAYER_TEXT_MESSAGE 0u
#define DF_PLAYER_TEXT_TIP 1u
#define DF_PLAYER_TEXT_POPUP 2u
#define DF_PLAYER_TEXT_JUKEBOX_POPUP 3u
#define DF_PLAYER_TEXT_NAME_TAG 4u
#define DF_PLAYER_STATE_GAME_MODE 0u
#define DF_PLAYER_STATE_HEAL 1u
#define DF_PLAYER_STATE_HURT 2u
#define DF_PLAYER_STATE_FOOD 3u
#define DF_PLAYER_STATE_MAX_HEALTH 4u
#define DF_PLAYER_STATE_HEALTH 5u
#define DF_PLAYER_STATE_EXPERIENCE_LEVEL 6u
#define DF_PLAYER_STATE_EXPERIENCE_PROGRESS 7u
#define DF_PLAYER_STATE_SCALE 8u
#define DF_PLAYER_STATE_INVISIBLE 9u
#define DF_PLAYER_STATE_IMMOBILE 10u
#define DF_EFFECT_SPEED 1u
#define DF_EFFECT_SLOWNESS 2u
#define DF_EFFECT_HASTE 3u
#define DF_EFFECT_MINING_FATIGUE 4u
#define DF_EFFECT_STRENGTH 5u
#define DF_EFFECT_INSTANT_HEALTH 6u
#define DF_EFFECT_INSTANT_DAMAGE 7u
#define DF_EFFECT_JUMP_BOOST 8u
#define DF_EFFECT_NAUSEA 9u
#define DF_EFFECT_REGENERATION 10u
#define DF_EFFECT_RESISTANCE 11u
#define DF_EFFECT_FIRE_RESISTANCE 12u
#define DF_EFFECT_WATER_BREATHING 13u
#define DF_EFFECT_INVISIBILITY 14u
#define DF_EFFECT_BLINDNESS 15u
#define DF_EFFECT_NIGHT_VISION 16u
#define DF_EFFECT_HUNGER 17u
#define DF_EFFECT_WEAKNESS 18u
#define DF_EFFECT_POISON 19u
#define DF_EFFECT_WITHER 20u
#define DF_EFFECT_HEALTH_BOOST 21u
#define DF_EFFECT_ABSORPTION 22u
#define DF_EFFECT_SATURATION 23u
#define DF_EFFECT_LEVITATION 24u
#define DF_EFFECT_FATAL_POISON 25u
#define DF_EFFECT_CONDUIT_POWER 26u
#define DF_EFFECT_SLOW_FALLING 27u
#define DF_EFFECT_DARKNESS 30u

typedef struct { DfStringView text; DfStringView subtitle; DfStringView action_text; uint64_t fade_in_milliseconds; uint64_t duration_milliseconds; uint64_t fade_out_milliseconds; } DfTitleView;
typedef struct { double number; int64_t integer; } DfPlayerStateValue;
#define DF_PLAYER_EFFECT_ADD 0u
#define DF_PLAYER_EFFECT_REMOVE 1u
typedef struct { uint32_t effect_type; int32_t level; uint64_t duration_milliseconds; uint8_t ambient; uint8_t infinite; uint8_t particles_hidden; } DfEffectView;
typedef DfStatus (*DfHostPlayerTextFn)(uint64_t context, DfPlayerId player, uint32_t kind, DfStringView message);
typedef DfStatus (*DfHostPlayerTitleFn)(uint64_t context, DfPlayerId player, DfTitleView title);
typedef DfStatus (*DfHostPlayerTransformFn)(uint64_t context, DfPlayerId player, uint32_t kind, DfVec3 vector, double yaw, double pitch);
typedef DfStatus (*DfHostPlayerRotationFn)(uint64_t context, DfPlayerId player, DfRotation *rotation);
typedef DfStatus (*DfHostPlayerStateSetFn)(uint64_t context, DfPlayerId player, uint32_t kind, DfPlayerStateValue value);
typedef DfStatus (*DfHostPlayerStateGetFn)(uint64_t context, DfPlayerId player, uint32_t kind, DfPlayerStateValue *value);
typedef DfStatus (*DfHostPlayerEffectFn)(uint64_t context, DfPlayerId player, uint32_t operation, DfEffectView effect);
typedef struct {
    uint32_t abi_version;
    uint32_t struct_size;
    uint64_t context;
    DfHostPlayerTextFn player_text;
    DfHostPlayerTitleFn player_title;
    DfHostPlayerTransformFn player_transform;
    DfHostPlayerRotationFn player_rotation;
    DfHostPlayerStateSetFn player_state_set;
    DfHostPlayerStateGetFn player_state_get;
    DfHostPlayerEffectFn player_effect;
} DfHostApiV1;
#define DF_COMMAND_PARAMETER_SUBCOMMAND 1u
#define DF_COMMAND_PARAMETER_ENUM 2u
#define DF_COMMAND_PARAMETER_STRING 3u
#define DF_COMMAND_PARAMETER_INTEGER 4u
#define DF_COMMAND_PARAMETER_FLOAT 5u
#define DF_COMMAND_PARAMETER_BOOL 6u
#define DF_COMMAND_PARAMETER_DYNAMIC_ENUM 7u
#define DF_COMMAND_PARAMETER_PLAYER 8u
#define DF_COMMAND_PARAMETER_RAW_TEXT 9u
typedef struct { uint32_t kind; uint8_t optional; DfStringView name; const DfStringView *values; uint64_t value_count; } DfCommandParameter;
typedef struct { const DfCommandParameter *parameters; uint64_t parameter_count; } DfCommandOverload;
typedef struct { DfStringView name; DfStringView description; const DfCommandOverload *overloads; uint64_t overload_count; } DfCommandDescriptor;
typedef struct { DfStringView source; const DfStringView *online_players; uint64_t online_player_count; } DfCommandEnumContext;
typedef struct { DfPlayerId player; DfStringView name; uint64_t latency_milliseconds; } DfCommandPlayer;
#define DF_COMMAND_SOURCE_UNKNOWN 0u
#define DF_COMMAND_SOURCE_PLAYER 1u
#define DF_COMMAND_SOURCE_CONSOLE 2u
typedef struct { DfStringView source; DfStringView arguments; uint32_t source_kind; DfPlayerId source_player; const DfCommandPlayer *online_players; uint64_t online_player_count; } DfCommandInput;
typedef struct { uint8_t failed; DfStringBuffer output; } DfCommandState;

typedef struct {
    uint32_t abi_version;
    uint32_t struct_size;
    uint64_t subscriptions;
} DfAbiHeader;

#define DF_EVENT_PLAYER_MOVE 1u

typedef struct {
    DfPlayerId player;
    DfVec3 old_position;
    DfVec3 new_position;
    DfRotation rotation;
} DfPlayerMoveInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerMoveState;

#define DF_EVENT_PLAYER_CHAT 2u

typedef struct {
    DfPlayerId player;
    DfStringView message;
} DfPlayerChatInput;

typedef struct {
    uint8_t cancelled;
    uint8_t has_replacement;
    DfStringBuffer replacement;
} DfPlayerChatState;

#define DF_EVENT_PLAYER_JOIN 3u

typedef struct {
    DfPlayerId player;
    DfStringView name;
} DfPlayerJoinInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerJoinState;

#define DF_EVENT_PLAYER_QUIT 4u

typedef struct {
    DfPlayerId player;
    DfStringView name;
} DfPlayerQuitInput;

typedef struct {
    uint8_t _reserved;
} DfPlayerQuitState;

#define DF_EVENT_PLAYER_HURT 5u

typedef struct {
    DfPlayerId player;
    uint8_t immune;
    DfStringView source;
} DfPlayerHurtInput;

typedef struct {
    uint8_t cancelled;
    double damage;
    uint64_t attack_immunity_milliseconds;
} DfPlayerHurtState;

#define DF_EVENT_PLAYER_HEAL 6u

typedef struct {
    DfPlayerId player;
    DfStringView source;
} DfPlayerHealInput;

typedef struct {
    uint8_t cancelled;
    double health;
} DfPlayerHealState;

#define DF_EVENT_PLAYER_BLOCK_BREAK 7u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
    DfStringView block;
} DfPlayerBlockBreakInput;

typedef struct {
    uint8_t cancelled;
    int32_t experience;
} DfPlayerBlockBreakState;

#define DF_EVENT_PLAYER_BLOCK_PLACE 8u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
    DfStringView block;
} DfPlayerBlockPlaceInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerBlockPlaceState;

#define DF_EVENT_PLAYER_FOOD_LOSS 9u

typedef struct {
    DfPlayerId player;
    int32_t from;
} DfPlayerFoodLossInput;

typedef struct {
    uint8_t cancelled;
    int32_t to;
} DfPlayerFoodLossState;

#define DF_EVENT_PLAYER_DEATH 10u

typedef struct {
    DfPlayerId player;
    DfStringView source;
} DfPlayerDeathInput;

typedef struct {
    uint8_t keep_inventory;
} DfPlayerDeathState;

#define DF_EVENT_PLAYER_START_BREAK 11u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
} DfPlayerStartBreakInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerStartBreakState;

#define DF_EVENT_PLAYER_FIRE_EXTINGUISH 12u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
} DfPlayerFireExtinguishInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerFireExtinguishState;

#define DF_EVENT_PLAYER_TOGGLE_SPRINT 13u

typedef struct {
    DfPlayerId player;
    uint8_t after;
} DfPlayerToggleSprintInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerToggleSprintState;

#define DF_EVENT_PLAYER_TOGGLE_SNEAK 14u

typedef struct {
    DfPlayerId player;
    uint8_t after;
} DfPlayerToggleSneakInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerToggleSneakState;

#define DF_EVENT_PLAYER_JUMP 15u

typedef struct {
    DfPlayerId player;
} DfPlayerJumpInput;

typedef struct {
    uint8_t _reserved;
} DfPlayerJumpState;

#define DF_EVENT_PLAYER_TELEPORT 16u

typedef struct {
    DfPlayerId player;
    DfVec3 position;
} DfPlayerTeleportInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerTeleportState;

#define DF_EVENT_PLAYER_EXPERIENCE_GAIN 17u

typedef struct {
    DfPlayerId player;
} DfPlayerExperienceGainInput;

typedef struct {
    uint8_t cancelled;
    int32_t amount;
} DfPlayerExperienceGainState;

#define DF_EVENT_PLAYER_PUNCH_AIR 18u

typedef struct {
    DfPlayerId player;
} DfPlayerPunchAirInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerPunchAirState;

#define DF_EVENT_PLAYER_HELD_SLOT_CHANGE 19u

typedef struct {
    DfPlayerId player;
    int32_t from;
    int32_t to;
} DfPlayerHeldSlotChangeInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerHeldSlotChangeState;

#define DF_EVENT_PLAYER_SLEEP 20u

typedef struct {
    DfPlayerId player;
} DfPlayerSleepInput;

typedef struct {
    uint8_t cancelled;
    uint8_t send_reminder;
} DfPlayerSleepState;

#define DF_EVENT_PLAYER_BLOCK_PICK 21u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
    DfStringView block;
} DfPlayerBlockPickInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerBlockPickState;

#define DF_EVENT_PLAYER_LECTERN_PAGE_TURN 22u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
    int32_t old_page;
} DfPlayerLecternPageTurnInput;

typedef struct {
    uint8_t cancelled;
    int32_t new_page;
} DfPlayerLecternPageTurnState;

#define DF_EVENT_PLAYER_SIGN_EDIT 23u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
    uint8_t front_side;
    DfStringView old_text;
    DfStringView new_text;
} DfPlayerSignEditInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerSignEditState;

#define DF_EVENT_PLAYER_ITEM_USE 24u

typedef struct {
    DfPlayerId player;
} DfPlayerItemUseInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerItemUseState;

#define DF_EVENT_PLAYER_ITEM_USE_ON_BLOCK 25u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
    int32_t face;
    DfVec3 click_position;
} DfPlayerItemUseOnBlockInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerItemUseOnBlockState;

#define DF_EVENT_PLAYER_ITEM_CONSUME 26u

typedef struct {
    DfPlayerId player;
    DfItemStackView item;
} DfPlayerItemConsumeInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerItemConsumeState;

#define DF_EVENT_PLAYER_ITEM_RELEASE 27u

typedef struct {
    DfPlayerId player;
    DfItemStackView item;
    uint64_t duration_milliseconds;
} DfPlayerItemReleaseInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerItemReleaseState;

#define DF_EVENT_PLAYER_ITEM_DAMAGE 28u

typedef struct {
    DfPlayerId player;
    DfItemStackView item;
} DfPlayerItemDamageInput;

typedef struct {
    uint8_t cancelled;
    int32_t damage;
} DfPlayerItemDamageState;

#define DF_EVENT_PLAYER_ITEM_DROP 29u

typedef struct {
    DfPlayerId player;
    DfItemStackView item;
} DfPlayerItemDropInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerItemDropState;

typedef DfStatus (*DfHandleEventFn)(void *instance, DfEventId event_id, const void *input, void *state);
typedef void *(*DfPluginCreateFn)(void);
typedef DfStatus (*DfPluginLifecycleFn)(void *instance);
typedef const DfCommandDescriptor *(*DfPluginCommandsFn)(void *instance, uint64_t *count);
typedef DfStatus (*DfHandleCommandFn)(void *instance, uint64_t command, const DfCommandInput *input, DfCommandState *state);
typedef DfStatus (*DfCommandEnumOptionsFn)(void *instance, uint64_t command, uint64_t overload, uint64_t parameter, const DfCommandEnumContext *context, DfStringBuffer *output);
typedef DfStatus (*DfPluginSetHostFn)(void *instance, const DfHostApiV1 *host);
typedef void (*DfPluginDestroyFn)(void *instance);

typedef struct {
    DfAbiHeader header;
    DfStringView plugin_id;
    DfPluginCreateFn create;
    DfPluginLifecycleFn enable;
    DfPluginLifecycleFn disable;
    DfPluginCommandsFn commands;
    DfHandleCommandFn handle_command;
    DfCommandEnumOptionsFn command_enum_options;
    DfPluginSetHostFn set_host;
    DfPluginDestroyFn destroy;
    DfHandleEventFn handle_event;
} DfPluginApiV1;

typedef const DfPluginApiV1 *(*DfPluginEntryV1Fn)(void);

typedef struct DfRuntime DfRuntime;
typedef struct { DfStringView plugin_directory; const DfHostApiV1 *host; } DfRuntimeConfig;

DfStatus df_runtime_create(const DfRuntimeConfig *config, DfRuntime **out, uint8_t *error, uint64_t error_capacity);
DfStatus df_runtime_enable(DfRuntime *runtime);
void df_runtime_disable(DfRuntime *runtime);
void df_runtime_destroy(DfRuntime *runtime);
uint64_t df_runtime_plugin_count(const DfRuntime *runtime);
uint64_t df_runtime_subscriptions(const DfRuntime *runtime);
uint64_t df_runtime_command_count(const DfRuntime *runtime);
DfStatus df_runtime_command_at(const DfRuntime *runtime, uint64_t index, DfCommandDescriptor *out);
DfStatus df_runtime_handle_command(DfRuntime *runtime, uint64_t index, const DfCommandInput *input, DfCommandState *state);
DfStatus df_runtime_command_enum_options(DfRuntime *runtime, uint64_t index, uint64_t overload, uint64_t parameter, const DfCommandEnumContext *context, DfStringBuffer *output);
DfStatus df_runtime_handle_event(DfRuntime *runtime, DfEventId event_id, const void *input, void *state);

#ifdef __cplusplus
}
#endif

#endif
