/* Code generated by abi-gen v1. DO NOT EDIT. */
#ifndef BEDROCK_GOPHERS_DRAGONFLY_PLUGIN_H
#define BEDROCK_GOPHERS_DRAGONFLY_PLUGIN_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DF_ABI_VERSION 1u
#define DF_STATUS_OK 0
#define DF_STATUS_ERROR 1

typedef int32_t DfStatus;
typedef uint32_t DfEventId;

typedef struct { uint8_t bytes[16]; uint64_t generation; } DfPlayerId;
typedef struct { double x; double y; double z; } DfVec3;
typedef struct { float yaw; float pitch; } DfRotation;
typedef struct { int32_t x; int32_t y; int32_t z; } DfBlockPos;
typedef struct { const uint8_t *data; uint64_t len; } DfStringView;
typedef struct { uint8_t *data; uint64_t len; uint64_t capacity; } DfStringBuffer;
#define DF_COMMAND_PARAMETER_SUBCOMMAND 1u
#define DF_COMMAND_PARAMETER_ENUM 2u
#define DF_COMMAND_PARAMETER_STRING 3u
#define DF_COMMAND_PARAMETER_INTEGER 4u
#define DF_COMMAND_PARAMETER_FLOAT 5u
#define DF_COMMAND_PARAMETER_BOOL 6u
#define DF_COMMAND_PARAMETER_DYNAMIC_ENUM 7u
#define DF_COMMAND_PARAMETER_PLAYER 8u
#define DF_COMMAND_PARAMETER_RAW_TEXT 9u
typedef struct { uint32_t kind; uint8_t optional; DfStringView name; const DfStringView *values; uint64_t value_count; } DfCommandParameter;
typedef struct { const DfCommandParameter *parameters; uint64_t parameter_count; } DfCommandOverload;
typedef struct { DfStringView name; DfStringView description; const DfCommandOverload *overloads; uint64_t overload_count; } DfCommandDescriptor;
typedef struct { DfStringView source; const DfStringView *online_players; uint64_t online_player_count; } DfCommandEnumContext;
typedef struct { DfPlayerId player; DfStringView name; uint64_t latency_milliseconds; } DfCommandPlayer;
#define DF_COMMAND_SOURCE_UNKNOWN 0u
#define DF_COMMAND_SOURCE_PLAYER 1u
#define DF_COMMAND_SOURCE_CONSOLE 2u
typedef struct { DfStringView source; DfStringView arguments; uint32_t source_kind; DfPlayerId source_player; const DfCommandPlayer *online_players; uint64_t online_player_count; } DfCommandInput;
typedef struct { uint8_t failed; DfStringBuffer output; } DfCommandState;

typedef struct {
    uint32_t abi_version;
    uint32_t struct_size;
    uint64_t subscriptions;
} DfAbiHeader;

#define DF_EVENT_PLAYER_MOVE 1u

typedef struct {
    DfPlayerId player;
    DfVec3 old_position;
    DfVec3 new_position;
    DfRotation rotation;
} DfPlayerMoveInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerMoveState;

#define DF_EVENT_PLAYER_CHAT 2u

typedef struct {
    DfPlayerId player;
    DfStringView message;
} DfPlayerChatInput;

typedef struct {
    uint8_t cancelled;
    uint8_t has_replacement;
    DfStringBuffer replacement;
} DfPlayerChatState;

#define DF_EVENT_PLAYER_JOIN 3u

typedef struct {
    DfPlayerId player;
    DfStringView name;
} DfPlayerJoinInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerJoinState;

#define DF_EVENT_PLAYER_QUIT 4u

typedef struct {
    DfPlayerId player;
    DfStringView name;
} DfPlayerQuitInput;

typedef struct {
    uint8_t _reserved;
} DfPlayerQuitState;

#define DF_EVENT_PLAYER_HURT 5u

typedef struct {
    DfPlayerId player;
    uint8_t immune;
    DfStringView source;
} DfPlayerHurtInput;

typedef struct {
    uint8_t cancelled;
    double damage;
    uint64_t attack_immunity_milliseconds;
} DfPlayerHurtState;

#define DF_EVENT_PLAYER_HEAL 6u

typedef struct {
    DfPlayerId player;
    DfStringView source;
} DfPlayerHealInput;

typedef struct {
    uint8_t cancelled;
    double health;
} DfPlayerHealState;

#define DF_EVENT_PLAYER_BLOCK_BREAK 7u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
    DfStringView block;
} DfPlayerBlockBreakInput;

typedef struct {
    uint8_t cancelled;
    int32_t experience;
} DfPlayerBlockBreakState;

#define DF_EVENT_PLAYER_BLOCK_PLACE 8u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
    DfStringView block;
} DfPlayerBlockPlaceInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerBlockPlaceState;

#define DF_EVENT_PLAYER_FOOD_LOSS 9u

typedef struct {
    DfPlayerId player;
    int32_t from;
} DfPlayerFoodLossInput;

typedef struct {
    uint8_t cancelled;
    int32_t to;
} DfPlayerFoodLossState;

#define DF_EVENT_PLAYER_DEATH 10u

typedef struct {
    DfPlayerId player;
    DfStringView source;
} DfPlayerDeathInput;

typedef struct {
    uint8_t keep_inventory;
} DfPlayerDeathState;

#define DF_EVENT_PLAYER_START_BREAK 11u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
} DfPlayerStartBreakInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerStartBreakState;

#define DF_EVENT_PLAYER_FIRE_EXTINGUISH 12u

typedef struct {
    DfPlayerId player;
    DfBlockPos position;
} DfPlayerFireExtinguishInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerFireExtinguishState;

#define DF_EVENT_PLAYER_TOGGLE_SPRINT 13u

typedef struct {
    DfPlayerId player;
    uint8_t after;
} DfPlayerToggleSprintInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerToggleSprintState;

#define DF_EVENT_PLAYER_TOGGLE_SNEAK 14u

typedef struct {
    DfPlayerId player;
    uint8_t after;
} DfPlayerToggleSneakInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerToggleSneakState;

#define DF_EVENT_PLAYER_JUMP 15u

typedef struct {
    DfPlayerId player;
} DfPlayerJumpInput;

typedef struct {
    uint8_t _reserved;
} DfPlayerJumpState;

#define DF_EVENT_PLAYER_TELEPORT 16u

typedef struct {
    DfPlayerId player;
    DfVec3 position;
} DfPlayerTeleportInput;

typedef struct {
    uint8_t cancelled;
} DfPlayerTeleportState;

typedef DfStatus (*DfHandleEventFn)(void *instance, DfEventId event_id, const void *input, void *state);
typedef void *(*DfPluginCreateFn)(void);
typedef DfStatus (*DfPluginLifecycleFn)(void *instance);
typedef const DfCommandDescriptor *(*DfPluginCommandsFn)(void *instance, uint64_t *count);
typedef DfStatus (*DfHandleCommandFn)(void *instance, uint64_t command, const DfCommandInput *input, DfCommandState *state);
typedef DfStatus (*DfCommandEnumOptionsFn)(void *instance, uint64_t command, uint64_t overload, uint64_t parameter, const DfCommandEnumContext *context, DfStringBuffer *output);
typedef void (*DfPluginDestroyFn)(void *instance);

typedef struct {
    DfAbiHeader header;
    DfStringView plugin_id;
    DfPluginCreateFn create;
    DfPluginLifecycleFn enable;
    DfPluginLifecycleFn disable;
    DfPluginCommandsFn commands;
    DfHandleCommandFn handle_command;
    DfCommandEnumOptionsFn command_enum_options;
    DfPluginDestroyFn destroy;
    DfHandleEventFn handle_event;
} DfPluginApiV1;

typedef const DfPluginApiV1 *(*DfPluginEntryV1Fn)(void);

typedef struct DfRuntime DfRuntime;
typedef struct { DfStringView plugin_directory; } DfRuntimeConfig;

DfStatus df_runtime_create(const DfRuntimeConfig *config, DfRuntime **out, uint8_t *error, uint64_t error_capacity);
DfStatus df_runtime_enable(DfRuntime *runtime);
void df_runtime_disable(DfRuntime *runtime);
void df_runtime_destroy(DfRuntime *runtime);
uint64_t df_runtime_plugin_count(const DfRuntime *runtime);
uint64_t df_runtime_subscriptions(const DfRuntime *runtime);
uint64_t df_runtime_command_count(const DfRuntime *runtime);
DfStatus df_runtime_command_at(const DfRuntime *runtime, uint64_t index, DfCommandDescriptor *out);
DfStatus df_runtime_handle_command(DfRuntime *runtime, uint64_t index, const DfCommandInput *input, DfCommandState *state);
DfStatus df_runtime_command_enum_options(DfRuntime *runtime, uint64_t index, uint64_t overload, uint64_t parameter, const DfCommandEnumContext *context, DfStringBuffer *output);
DfStatus df_runtime_handle_player_move(DfRuntime *runtime, const DfPlayerMoveInput *input, DfPlayerMoveState *state);
DfStatus df_runtime_handle_player_chat(DfRuntime *runtime, const DfPlayerChatInput *input, DfPlayerChatState *state);
DfStatus df_runtime_handle_player_join(DfRuntime *runtime, const DfPlayerJoinInput *input, DfPlayerJoinState *state);
DfStatus df_runtime_handle_player_quit(DfRuntime *runtime, const DfPlayerQuitInput *input, DfPlayerQuitState *state);
DfStatus df_runtime_handle_player_hurt(DfRuntime *runtime, const DfPlayerHurtInput *input, DfPlayerHurtState *state);
DfStatus df_runtime_handle_player_heal(DfRuntime *runtime, const DfPlayerHealInput *input, DfPlayerHealState *state);
DfStatus df_runtime_handle_player_block_break(DfRuntime *runtime, const DfPlayerBlockBreakInput *input, DfPlayerBlockBreakState *state);
DfStatus df_runtime_handle_player_block_place(DfRuntime *runtime, const DfPlayerBlockPlaceInput *input, DfPlayerBlockPlaceState *state);
DfStatus df_runtime_handle_player_food_loss(DfRuntime *runtime, const DfPlayerFoodLossInput *input, DfPlayerFoodLossState *state);
DfStatus df_runtime_handle_player_death(DfRuntime *runtime, const DfPlayerDeathInput *input, DfPlayerDeathState *state);
DfStatus df_runtime_handle_player_start_break(DfRuntime *runtime, const DfPlayerStartBreakInput *input, DfPlayerStartBreakState *state);
DfStatus df_runtime_handle_player_fire_extinguish(DfRuntime *runtime, const DfPlayerFireExtinguishInput *input, DfPlayerFireExtinguishState *state);
DfStatus df_runtime_handle_player_toggle_sprint(DfRuntime *runtime, const DfPlayerToggleSprintInput *input, DfPlayerToggleSprintState *state);
DfStatus df_runtime_handle_player_toggle_sneak(DfRuntime *runtime, const DfPlayerToggleSneakInput *input, DfPlayerToggleSneakState *state);
DfStatus df_runtime_handle_player_jump(DfRuntime *runtime, const DfPlayerJumpInput *input, DfPlayerJumpState *state);
DfStatus df_runtime_handle_player_teleport(DfRuntime *runtime, const DfPlayerTeleportInput *input, DfPlayerTeleportState *state);

#ifdef __cplusplus
}
#endif

#endif
