// Command abi-gen generates language-neutral native ABI types from schema.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const generatorVersion = "1"

type schemaFile struct {
	Domain string  `yaml:"domain"`
	Events []event `yaml:"events"`
}

type event struct {
	Domain string
	Name   string  `yaml:"name"`
	ID     uint32  `yaml:"id"`
	Input  []field `yaml:"input"`
	State  []field `yaml:"state"`
}

type field struct {
	Name string `yaml:"name"`
	Type string `yaml:"type"`
}

func main() {
	root := flag.String("root", ".", "repository root")
	check := flag.Bool("check", false, "fail if generated files are stale")
	flag.Parse()

	events, err := readEvents(filepath.Join(*root, "schema", "events"))
	if err != nil {
		fatal(err)
	}
	outputs := map[string][]byte{
		filepath.Join(*root, "abi", "include", "dragonfly_plugin.h"):                generateC(events),
		filepath.Join(*root, "rust", "dragonfly-plugin-sys", "src", "generated.rs"): generateRust(events),
	}
	for path, data := range outputs {
		if strings.HasSuffix(path, ".rs") {
			// Rustfmt runs later through Cargo. Keep generated source deterministic here.
			data = bytes.TrimSpace(data)
			data = append(data, '\n')
		}
		if err := writeGenerated(path, data, *check); err != nil {
			fatal(err)
		}
	}
}

func readEvents(dir string) ([]event, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var events []event
	ids := map[uint32]string{}
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yaml") {
			continue
		}
		path := filepath.Join(dir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		var file schemaFile
		if err := yaml.Unmarshal(data, &file); err != nil {
			return nil, fmt.Errorf("decode %s: %w", path, err)
		}
		if file.Domain == "" {
			return nil, fmt.Errorf("%s: empty domain", path)
		}
		for _, evt := range file.Events {
			evt.Domain = file.Domain
			fullName := evt.Domain + "_" + evt.Name
			if previous, ok := ids[evt.ID]; ok {
				return nil, fmt.Errorf("event ID %d used by %s and %s", evt.ID, previous, fullName)
			}
			ids[evt.ID] = fullName
			if err := validateFields(fullName, append(append([]field{}, evt.Input...), evt.State...)); err != nil {
				return nil, err
			}
			events = append(events, evt)
		}
	}
	sort.Slice(events, func(i, j int) bool { return events[i].ID < events[j].ID })
	return events, nil
}

func validateFields(eventName string, fields []field) error {
	valid := map[string]bool{
		"bool": true, "player_id": true, "rotation": true, "string_buffer": true,
		"string_view": true, "vec3": true,
	}
	seen := map[string]bool{}
	for _, f := range fields {
		if f.Name == "" || !valid[f.Type] {
			return fmt.Errorf("event %s: invalid field %q type %q", eventName, f.Name, f.Type)
		}
		if seen[f.Name] {
			return fmt.Errorf("event %s: duplicate field %q", eventName, f.Name)
		}
		seen[f.Name] = true
	}
	return nil
}

func generateC(events []event) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "/* Code generated by abi-gen v%s. DO NOT EDIT. */\n", generatorVersion)
	b.WriteString(`#ifndef BEDROCK_GOPHERS_DRAGONFLY_PLUGIN_H
#define BEDROCK_GOPHERS_DRAGONFLY_PLUGIN_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define DF_ABI_VERSION 1u
#define DF_STATUS_OK 0
#define DF_STATUS_ERROR 1

typedef int32_t DfStatus;
typedef uint32_t DfEventId;

typedef struct { uint8_t bytes[16]; uint64_t generation; } DfPlayerId;
typedef struct { double x; double y; double z; } DfVec3;
typedef struct { float yaw; float pitch; } DfRotation;
typedef struct { const uint8_t *data; uint64_t len; } DfStringView;
typedef struct { uint8_t *data; uint64_t len; uint64_t capacity; } DfStringBuffer;
#define DF_COMMAND_PARAMETER_SUBCOMMAND 1u
#define DF_COMMAND_PARAMETER_ENUM 2u
#define DF_COMMAND_PARAMETER_STRING 3u
#define DF_COMMAND_PARAMETER_INTEGER 4u
#define DF_COMMAND_PARAMETER_FLOAT 5u
#define DF_COMMAND_PARAMETER_BOOL 6u
#define DF_COMMAND_PARAMETER_DYNAMIC_ENUM 7u
#define DF_COMMAND_PARAMETER_PLAYER 8u
#define DF_COMMAND_PARAMETER_RAW_TEXT 9u
typedef struct { uint32_t kind; uint8_t optional; DfStringView name; const DfStringView *values; uint64_t value_count; } DfCommandParameter;
typedef struct { const DfCommandParameter *parameters; uint64_t parameter_count; } DfCommandOverload;
typedef struct { DfStringView name; DfStringView description; const DfCommandOverload *overloads; uint64_t overload_count; } DfCommandDescriptor;
typedef struct { DfStringView source; const DfStringView *online_players; uint64_t online_player_count; } DfCommandEnumContext;
typedef struct { DfPlayerId player; DfStringView name; uint64_t latency_milliseconds; } DfCommandPlayer;
#define DF_COMMAND_SOURCE_UNKNOWN 0u
#define DF_COMMAND_SOURCE_PLAYER 1u
#define DF_COMMAND_SOURCE_CONSOLE 2u
typedef struct { DfStringView source; DfStringView arguments; uint32_t source_kind; DfPlayerId source_player; const DfCommandPlayer *online_players; uint64_t online_player_count; } DfCommandInput;
typedef struct { uint8_t failed; DfStringBuffer output; } DfCommandState;

typedef struct {
    uint32_t abi_version;
    uint32_t struct_size;
    uint64_t subscriptions;
} DfAbiHeader;

`)
	for _, evt := range events {
		upper := strings.ToUpper(evt.Domain + "_" + evt.Name)
		name := cName(evt)
		fmt.Fprintf(&b, "#define DF_EVENT_%s %du\n\n", upper, evt.ID)
		fmt.Fprintf(&b, "typedef struct {\n")
		if len(evt.Input) == 0 {
			fmt.Fprintf(&b, "    uint8_t _reserved;\n")
		}
		for _, f := range evt.Input {
			fmt.Fprintf(&b, "    %s %s;\n", cType(f.Type), f.Name)
		}
		fmt.Fprintf(&b, "} %sInput;\n\n", name)
		fmt.Fprintf(&b, "typedef struct {\n")
		if len(evt.State) == 0 {
			fmt.Fprintf(&b, "    uint8_t _reserved;\n")
		}
		for _, f := range evt.State {
			fmt.Fprintf(&b, "    %s %s;\n", cType(f.Type), f.Name)
		}
		fmt.Fprintf(&b, "} %sState;\n\n", name)
	}
	b.WriteString(`typedef DfStatus (*DfHandleEventFn)(void *instance, DfEventId event_id, const void *input, void *state);
typedef void *(*DfPluginCreateFn)(void);
typedef DfStatus (*DfPluginLifecycleFn)(void *instance);
typedef const DfCommandDescriptor *(*DfPluginCommandsFn)(void *instance, uint64_t *count);
typedef DfStatus (*DfHandleCommandFn)(void *instance, uint64_t command, const DfCommandInput *input, DfCommandState *state);
typedef DfStatus (*DfCommandEnumOptionsFn)(void *instance, uint64_t command, uint64_t overload, uint64_t parameter, const DfCommandEnumContext *context, DfStringBuffer *output);
typedef void (*DfPluginDestroyFn)(void *instance);

typedef struct {
    DfAbiHeader header;
    DfStringView plugin_id;
    DfPluginCreateFn create;
    DfPluginLifecycleFn enable;
    DfPluginLifecycleFn disable;
    DfPluginCommandsFn commands;
    DfHandleCommandFn handle_command;
    DfCommandEnumOptionsFn command_enum_options;
    DfPluginDestroyFn destroy;
    DfHandleEventFn handle_event;
} DfPluginApiV1;

typedef const DfPluginApiV1 *(*DfPluginEntryV1Fn)(void);

typedef struct DfRuntime DfRuntime;
typedef struct { DfStringView plugin_directory; } DfRuntimeConfig;

DfStatus df_runtime_create(const DfRuntimeConfig *config, DfRuntime **out, uint8_t *error, uint64_t error_capacity);
DfStatus df_runtime_enable(DfRuntime *runtime);
void df_runtime_disable(DfRuntime *runtime);
void df_runtime_destroy(DfRuntime *runtime);
uint64_t df_runtime_plugin_count(const DfRuntime *runtime);
uint64_t df_runtime_subscriptions(const DfRuntime *runtime);
uint64_t df_runtime_command_count(const DfRuntime *runtime);
DfStatus df_runtime_command_at(const DfRuntime *runtime, uint64_t index, DfCommandDescriptor *out);
DfStatus df_runtime_handle_command(DfRuntime *runtime, uint64_t index, const DfCommandInput *input, DfCommandState *state);
DfStatus df_runtime_command_enum_options(DfRuntime *runtime, uint64_t index, uint64_t overload, uint64_t parameter, const DfCommandEnumContext *context, DfStringBuffer *output);
`)
	for _, evt := range events {
		name := cName(evt)
		fmt.Fprintf(&b, "DfStatus df_runtime_handle_%s(DfRuntime *runtime, const %sInput *input, %sState *state);\n", evt.Domain+"_"+evt.Name, name, name)
	}
	b.WriteString(`
#ifdef __cplusplus
}
#endif

#endif
`)
	return b.Bytes()
}

func generateRust(events []event) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by abi-gen v%s. DO NOT EDIT.\n\n", generatorVersion)
	b.WriteString(`use core::ffi::c_void;

pub const DF_ABI_VERSION: u32 = 1;
pub const DF_STATUS_OK: DfStatus = 0;
pub const DF_STATUS_ERROR: DfStatus = 1;
pub type DfStatus = i32;
pub type DfEventId = u32;

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerId { pub bytes: [u8; 16], pub generation: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfVec3 { pub x: f64, pub y: f64, pub z: f64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfRotation { pub yaw: f32, pub pitch: f32 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfStringView { pub data: *const u8, pub len: u64 }
impl Default for DfStringView {
    fn default() -> Self { Self { data: core::ptr::null(), len: 0 } }
}
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfStringBuffer { pub data: *mut u8, pub len: u64, pub capacity: u64 }
impl Default for DfStringBuffer {
    fn default() -> Self { Self { data: core::ptr::null_mut(), len: 0, capacity: 0 } }
}
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandParameter { pub kind: u32, pub optional: u8, pub name: DfStringView, pub values: *const DfStringView, pub value_count: u64 }
pub const DF_COMMAND_PARAMETER_SUBCOMMAND: u32 = 1;
pub const DF_COMMAND_PARAMETER_ENUM: u32 = 2;
pub const DF_COMMAND_PARAMETER_STRING: u32 = 3;
pub const DF_COMMAND_PARAMETER_INTEGER: u32 = 4;
pub const DF_COMMAND_PARAMETER_FLOAT: u32 = 5;
pub const DF_COMMAND_PARAMETER_BOOL: u32 = 6;
pub const DF_COMMAND_PARAMETER_DYNAMIC_ENUM: u32 = 7;
pub const DF_COMMAND_PARAMETER_PLAYER: u32 = 8;
pub const DF_COMMAND_PARAMETER_RAW_TEXT: u32 = 9;
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandOverload { pub parameters: *const DfCommandParameter, pub parameter_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandDescriptor { pub name: DfStringView, pub description: DfStringView, pub overloads: *const DfCommandOverload, pub overload_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandEnumContext { pub source: DfStringView, pub online_players: *const DfStringView, pub online_player_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandPlayer { pub player: DfPlayerId, pub name: DfStringView, pub latency_milliseconds: u64 }
pub const DF_COMMAND_SOURCE_UNKNOWN: u32 = 0;
pub const DF_COMMAND_SOURCE_PLAYER: u32 = 1;
pub const DF_COMMAND_SOURCE_CONSOLE: u32 = 2;
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandInput { pub source: DfStringView, pub arguments: DfStringView, pub source_kind: u32, pub source_player: DfPlayerId, pub online_players: *const DfCommandPlayer, pub online_player_count: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfCommandState { pub failed: u8, pub output: DfStringBuffer }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfAbiHeader { pub abi_version: u32, pub struct_size: u32, pub subscriptions: u64 }

`)
	for _, evt := range events {
		upper := strings.ToUpper(evt.Domain + "_" + evt.Name)
		name := rustName(evt)
		fmt.Fprintf(&b, "pub const DF_EVENT_%s: DfEventId = %d;\n", upper, evt.ID)
		fmt.Fprintf(&b, "pub const DF_SUBSCRIPTION_%s: u64 = 1u64 << %d;\n", upper, evt.ID-1)
		b.WriteString("#[repr(C)]\n#[derive(Clone, Copy, Debug, Default)]\n")
		fmt.Fprintf(&b, "pub struct %sInput {\n", name)
		if len(evt.Input) == 0 {
			b.WriteString("    pub _reserved: u8,\n")
		}
		for _, f := range evt.Input {
			fmt.Fprintf(&b, "    pub %s: %s,\n", f.Name, rustType(f.Type))
		}
		b.WriteString("}\n")
		b.WriteString("#[repr(C)]\n#[derive(Clone, Copy, Debug, Default)]\n")
		fmt.Fprintf(&b, "pub struct %sState {\n", name)
		if len(evt.State) == 0 {
			b.WriteString("    pub _reserved: u8,\n")
		}
		for _, f := range evt.State {
			fmt.Fprintf(&b, "    pub %s: %s,\n", f.Name, rustType(f.Type))
		}
		b.WriteString("}\n\n")
	}
	b.WriteString(`pub type DfPluginCreateFn = unsafe extern "C" fn() -> *mut c_void;
pub type DfPluginLifecycleFn = unsafe extern "C" fn(instance: *mut c_void) -> DfStatus;
pub type DfPluginCommandsFn = unsafe extern "C" fn(instance: *mut c_void, count: *mut u64) -> *const DfCommandDescriptor;
pub type DfHandleCommandFn = unsafe extern "C" fn(instance: *mut c_void, command: u64, input: *const DfCommandInput, state: *mut DfCommandState) -> DfStatus;
pub type DfCommandEnumOptionsFn = unsafe extern "C" fn(instance: *mut c_void, command: u64, overload: u64, parameter: u64, context: *const DfCommandEnumContext, output: *mut DfStringBuffer) -> DfStatus;
pub type DfPluginDestroyFn = unsafe extern "C" fn(instance: *mut c_void);
pub type DfHandleEventFn = unsafe extern "C" fn(instance: *mut c_void, event_id: DfEventId, input: *const c_void, state: *mut c_void) -> DfStatus;

#[repr(C)]
pub struct DfPluginApiV1 {
    pub header: DfAbiHeader,
    pub plugin_id: DfStringView,
    pub create: Option<DfPluginCreateFn>,
    pub enable: Option<DfPluginLifecycleFn>,
    pub disable: Option<DfPluginLifecycleFn>,
    pub commands: Option<DfPluginCommandsFn>,
    pub handle_command: Option<DfHandleCommandFn>,
    pub command_enum_options: Option<DfCommandEnumOptionsFn>,
    pub destroy: Option<DfPluginDestroyFn>,
    pub handle_event: Option<DfHandleEventFn>,
}

pub type DfPluginEntryV1Fn = unsafe extern "C" fn() -> *const DfPluginApiV1;

unsafe impl Sync for DfPluginApiV1 {}
`)
	return b.Bytes()
}

func cType(t string) string {
	return map[string]string{
		"bool": "uint8_t", "player_id": "DfPlayerId", "rotation": "DfRotation",
		"string_buffer": "DfStringBuffer", "string_view": "DfStringView", "vec3": "DfVec3",
	}[t]
}

func rustType(t string) string {
	return map[string]string{
		"bool": "u8", "player_id": "DfPlayerId", "rotation": "DfRotation",
		"string_buffer": "DfStringBuffer", "string_view": "DfStringView", "vec3": "DfVec3",
	}[t]
}

func cName(evt event) string    { return "Df" + title(evt.Domain) + title(evt.Name) }
func rustName(evt event) string { return "Df" + title(evt.Domain) + title(evt.Name) }
func title(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
	}
	return strings.Join(parts, "")
}

func writeGenerated(path string, data []byte, check bool) error {
	if strings.HasSuffix(path, ".go") {
		formatted, err := format.Source(data)
		if err != nil {
			return err
		}
		data = formatted
	}
	existing, err := os.ReadFile(path)
	if err == nil && bytes.Equal(existing, data) {
		return nil
	}
	if check {
		return fmt.Errorf("generated file is stale: %s", path)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "abi-gen:", err)
	os.Exit(1)
}
