// Code generated by abi-gen v1. DO NOT EDIT.

pub trait Item {
    fn identifier(&self) -> &str;

    fn metadata(&self) -> i16 { 0 }
}

impl<T: Item + ?Sized> Item for &T {
    fn identifier(&self) -> &str { (*self).identifier() }

    fn metadata(&self) -> i16 { (*self).metadata() }
}

pub mod item {
    use super::Item;

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Apple;

    impl Item for Apple {
        fn identifier(&self) -> &str { "minecraft:apple" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Arrow;

    impl Item for Arrow {
        fn identifier(&self) -> &str { "minecraft:arrow" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Book;

    impl Item for Book {
        fn identifier(&self) -> &str { "minecraft:book" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct BookAndQuill;

    impl Item for BookAndQuill {
        fn identifier(&self) -> &str { "minecraft:writable_book" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Bow;

    impl Item for Bow {
        fn identifier(&self) -> &str { "minecraft:bow" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Bread;

    impl Item for Bread {
        fn identifier(&self) -> &str { "minecraft:bread" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Bucket;

    impl Item for Bucket {
        fn identifier(&self) -> &str { "minecraft:bucket" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Clock;

    impl Item for Clock {
        fn identifier(&self) -> &str { "minecraft:clock" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Coal;

    impl Item for Coal {
        fn identifier(&self) -> &str { "minecraft:coal" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Compass;

    impl Item for Compass {
        fn identifier(&self) -> &str { "minecraft:compass" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Crossbow;

    impl Item for Crossbow {
        fn identifier(&self) -> &str { "minecraft:crossbow" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Diamond;

    impl Item for Diamond {
        fn identifier(&self) -> &str { "minecraft:diamond" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Egg;

    impl Item for Egg {
        fn identifier(&self) -> &str { "minecraft:egg" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Emerald;

    impl Item for Emerald {
        fn identifier(&self) -> &str { "minecraft:emerald" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct EnderPearl;

    impl Item for EnderPearl {
        fn identifier(&self) -> &str { "minecraft:ender_pearl" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct FlintAndSteel;

    impl Item for FlintAndSteel {
        fn identifier(&self) -> &str { "minecraft:flint_and_steel" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct GoldIngot;

    impl Item for GoldIngot {
        fn identifier(&self) -> &str { "minecraft:gold_ingot" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct GoldenApple;

    impl Item for GoldenApple {
        fn identifier(&self) -> &str { "minecraft:golden_apple" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct IronIngot;

    impl Item for IronIngot {
        fn identifier(&self) -> &str { "minecraft:iron_ingot" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct NetheriteIngot;

    impl Item for NetheriteIngot {
        fn identifier(&self) -> &str { "minecraft:netherite_ingot" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Paper;

    impl Item for Paper {
        fn identifier(&self) -> &str { "minecraft:paper" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Shears;

    impl Item for Shears {
        fn identifier(&self) -> &str { "minecraft:shears" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Snowball;

    impl Item for Snowball {
        fn identifier(&self) -> &str { "minecraft:snowball" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Stick;

    impl Item for Stick {
        fn identifier(&self) -> &str { "minecraft:stick" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct String;

    impl Item for String {
        fn identifier(&self) -> &str { "minecraft:string" }
    }

    #[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
    pub struct Totem;

    impl Item for Totem {
        fn identifier(&self) -> &str { "minecraft:totem_of_undying" }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub enum ToolTier {
        Wood,
        Gold,
        Stone,
        Copper,
        Iron,
        Diamond,
        Netherite,
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub struct Sword { tier: ToolTier }

    impl Sword {
        pub const fn new(tier: ToolTier) -> Self { Self { tier } }

        pub const fn tier(self) -> ToolTier { self.tier }
    }

    impl Item for Sword {
        fn identifier(&self) -> &str {
            match self.tier {
                ToolTier::Wood => "minecraft:wooden_sword",
                ToolTier::Gold => "minecraft:golden_sword",
                ToolTier::Stone => "minecraft:stone_sword",
                ToolTier::Copper => "minecraft:copper_sword",
                ToolTier::Iron => "minecraft:iron_sword",
                ToolTier::Diamond => "minecraft:diamond_sword",
                ToolTier::Netherite => "minecraft:netherite_sword",
            }
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub struct Pickaxe { tier: ToolTier }

    impl Pickaxe {
        pub const fn new(tier: ToolTier) -> Self { Self { tier } }

        pub const fn tier(self) -> ToolTier { self.tier }
    }

    impl Item for Pickaxe {
        fn identifier(&self) -> &str {
            match self.tier {
                ToolTier::Wood => "minecraft:wooden_pickaxe",
                ToolTier::Gold => "minecraft:golden_pickaxe",
                ToolTier::Stone => "minecraft:stone_pickaxe",
                ToolTier::Copper => "minecraft:copper_pickaxe",
                ToolTier::Iron => "minecraft:iron_pickaxe",
                ToolTier::Diamond => "minecraft:diamond_pickaxe",
                ToolTier::Netherite => "minecraft:netherite_pickaxe",
            }
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub struct Axe { tier: ToolTier }

    impl Axe {
        pub const fn new(tier: ToolTier) -> Self { Self { tier } }

        pub const fn tier(self) -> ToolTier { self.tier }
    }

    impl Item for Axe {
        fn identifier(&self) -> &str {
            match self.tier {
                ToolTier::Wood => "minecraft:wooden_axe",
                ToolTier::Gold => "minecraft:golden_axe",
                ToolTier::Stone => "minecraft:stone_axe",
                ToolTier::Copper => "minecraft:copper_axe",
                ToolTier::Iron => "minecraft:iron_axe",
                ToolTier::Diamond => "minecraft:diamond_axe",
                ToolTier::Netherite => "minecraft:netherite_axe",
            }
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub struct Shovel { tier: ToolTier }

    impl Shovel {
        pub const fn new(tier: ToolTier) -> Self { Self { tier } }

        pub const fn tier(self) -> ToolTier { self.tier }
    }

    impl Item for Shovel {
        fn identifier(&self) -> &str {
            match self.tier {
                ToolTier::Wood => "minecraft:wooden_shovel",
                ToolTier::Gold => "minecraft:golden_shovel",
                ToolTier::Stone => "minecraft:stone_shovel",
                ToolTier::Copper => "minecraft:copper_shovel",
                ToolTier::Iron => "minecraft:iron_shovel",
                ToolTier::Diamond => "minecraft:diamond_shovel",
                ToolTier::Netherite => "minecraft:netherite_shovel",
            }
        }
    }

    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub struct Hoe { tier: ToolTier }

    impl Hoe {
        pub const fn new(tier: ToolTier) -> Self { Self { tier } }

        pub const fn tier(self) -> ToolTier { self.tier }
    }

    impl Item for Hoe {
        fn identifier(&self) -> &str {
            match self.tier {
                ToolTier::Wood => "minecraft:wooden_hoe",
                ToolTier::Gold => "minecraft:golden_hoe",
                ToolTier::Stone => "minecraft:stone_hoe",
                ToolTier::Copper => "minecraft:copper_hoe",
                ToolTier::Iron => "minecraft:iron_hoe",
                ToolTier::Diamond => "minecraft:diamond_hoe",
                ToolTier::Netherite => "minecraft:netherite_hoe",
            }
        }
    }

    #[derive(Clone, Debug, Eq, Hash, PartialEq)]
    pub struct Custom { identifier: std::string::String, metadata: i16 }

    impl Custom {
        pub fn new(identifier: impl Into<std::string::String>) -> Self {
            Self { identifier: identifier.into(), metadata: 0 }
        }

        pub fn with_metadata(mut self, metadata: i16) -> Self {
            self.metadata = metadata;
            self
        }
    }

    impl Item for Custom {
        fn identifier(&self) -> &str { &self.identifier }

        fn metadata(&self) -> i16 { self.metadata }
    }

    pub fn new(item: impl Item, count: u32) -> super::ItemStack {
        super::ItemStack::new(item, count)
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Enchantment {
    Protection,
    FireProtection,
    FeatherFalling,
    BlastProtection,
    ProjectileProtection,
    Thorns,
    Respiration,
    DepthStrider,
    AquaAffinity,
    Sharpness,
    Knockback,
    FireAspect,
    Efficiency,
    SilkTouch,
    Unbreaking,
    Fortune,
    Power,
    Punch,
    Flame,
    Infinity,
    Mending,
    CurseOfVanishing,
    Multishot,
    Piercing,
    QuickCharge,
    SoulSpeed,
    SwiftSneak,
    Custom(u32),
}

impl Enchantment {
    pub const fn id(self) -> u32 {
        match self {
            Self::Protection => 0,
            Self::FireProtection => 1,
            Self::FeatherFalling => 2,
            Self::BlastProtection => 3,
            Self::ProjectileProtection => 4,
            Self::Thorns => 5,
            Self::Respiration => 6,
            Self::DepthStrider => 7,
            Self::AquaAffinity => 8,
            Self::Sharpness => 9,
            Self::Knockback => 12,
            Self::FireAspect => 13,
            Self::Efficiency => 15,
            Self::SilkTouch => 16,
            Self::Unbreaking => 17,
            Self::Fortune => 18,
            Self::Power => 19,
            Self::Punch => 20,
            Self::Flame => 21,
            Self::Infinity => 22,
            Self::Mending => 26,
            Self::CurseOfVanishing => 28,
            Self::Multishot => 33,
            Self::Piercing => 34,
            Self::QuickCharge => 35,
            Self::SoulSpeed => 36,
            Self::SwiftSneak => 37,
            Self::Custom(id) => id,
        }
    }

    pub const fn max_level(self) -> Option<u32> {
        match self {
            Self::Protection => Some(4),
            Self::FireProtection => Some(4),
            Self::FeatherFalling => Some(4),
            Self::BlastProtection => Some(4),
            Self::ProjectileProtection => Some(4),
            Self::Thorns => Some(3),
            Self::Respiration => Some(3),
            Self::DepthStrider => Some(3),
            Self::AquaAffinity => Some(1),
            Self::Sharpness => Some(5),
            Self::Knockback => Some(2),
            Self::FireAspect => Some(2),
            Self::Efficiency => Some(5),
            Self::SilkTouch => Some(1),
            Self::Unbreaking => Some(3),
            Self::Fortune => Some(3),
            Self::Power => Some(5),
            Self::Punch => Some(2),
            Self::Flame => Some(1),
            Self::Infinity => Some(1),
            Self::Mending => Some(1),
            Self::CurseOfVanishing => Some(1),
            Self::Multishot => Some(1),
            Self::Piercing => Some(4),
            Self::QuickCharge => Some(3),
            Self::SoulSpeed => Some(3),
            Self::SwiftSneak => Some(3),
            Self::Custom(_) => None,
        }
    }

    pub const fn from_id(id: u32) -> Self {
        match id {
            0 => Self::Protection,
            1 => Self::FireProtection,
            2 => Self::FeatherFalling,
            3 => Self::BlastProtection,
            4 => Self::ProjectileProtection,
            5 => Self::Thorns,
            6 => Self::Respiration,
            7 => Self::DepthStrider,
            8 => Self::AquaAffinity,
            9 => Self::Sharpness,
            12 => Self::Knockback,
            13 => Self::FireAspect,
            15 => Self::Efficiency,
            16 => Self::SilkTouch,
            17 => Self::Unbreaking,
            18 => Self::Fortune,
            19 => Self::Power,
            20 => Self::Punch,
            21 => Self::Flame,
            22 => Self::Infinity,
            26 => Self::Mending,
            28 => Self::CurseOfVanishing,
            33 => Self::Multishot,
            34 => Self::Piercing,
            35 => Self::QuickCharge,
            36 => Self::SoulSpeed,
            37 => Self::SwiftSneak,
            _ => Self::Custom(id),
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Potion {
    Water,
    Mundane,
    LongMundane,
    Thick,
    Awkward,
    NightVision,
    LongNightVision,
    Invisibility,
    LongInvisibility,
    Leaping,
    LongLeaping,
    StrongLeaping,
    FireResistance,
    LongFireResistance,
    Swiftness,
    LongSwiftness,
    StrongSwiftness,
    Slowness,
    LongSlowness,
    WaterBreathing,
    LongWaterBreathing,
    Healing,
    StrongHealing,
    Harming,
    StrongHarming,
    Poison,
    LongPoison,
    StrongPoison,
    Regeneration,
    LongRegeneration,
    StrongRegeneration,
    Strength,
    LongStrength,
    StrongStrength,
    Weakness,
    LongWeakness,
    Wither,
    TurtleMaster,
    LongTurtleMaster,
    StrongTurtleMaster,
    SlowFalling,
    LongSlowFalling,
    StrongSlowness,
    Custom(u8),
}

impl Potion {
    pub const fn id(self) -> u8 {
        match self {
            Self::Water => 0,
            Self::Mundane => 1,
            Self::LongMundane => 2,
            Self::Thick => 3,
            Self::Awkward => 4,
            Self::NightVision => 5,
            Self::LongNightVision => 6,
            Self::Invisibility => 7,
            Self::LongInvisibility => 8,
            Self::Leaping => 9,
            Self::LongLeaping => 10,
            Self::StrongLeaping => 11,
            Self::FireResistance => 12,
            Self::LongFireResistance => 13,
            Self::Swiftness => 14,
            Self::LongSwiftness => 15,
            Self::StrongSwiftness => 16,
            Self::Slowness => 17,
            Self::LongSlowness => 18,
            Self::WaterBreathing => 19,
            Self::LongWaterBreathing => 20,
            Self::Healing => 21,
            Self::StrongHealing => 22,
            Self::Harming => 23,
            Self::StrongHarming => 24,
            Self::Poison => 25,
            Self::LongPoison => 26,
            Self::StrongPoison => 27,
            Self::Regeneration => 28,
            Self::LongRegeneration => 29,
            Self::StrongRegeneration => 30,
            Self::Strength => 31,
            Self::LongStrength => 32,
            Self::StrongStrength => 33,
            Self::Weakness => 34,
            Self::LongWeakness => 35,
            Self::Wither => 36,
            Self::TurtleMaster => 37,
            Self::LongTurtleMaster => 38,
            Self::StrongTurtleMaster => 39,
            Self::SlowFalling => 40,
            Self::LongSlowFalling => 41,
            Self::StrongSlowness => 42,
            Self::Custom(id) => id,
        }
    }

    pub const fn from_id(id: u8) -> Self {
        match id {
            0 => Self::Water,
            1 => Self::Mundane,
            2 => Self::LongMundane,
            3 => Self::Thick,
            4 => Self::Awkward,
            5 => Self::NightVision,
            6 => Self::LongNightVision,
            7 => Self::Invisibility,
            8 => Self::LongInvisibility,
            9 => Self::Leaping,
            10 => Self::LongLeaping,
            11 => Self::StrongLeaping,
            12 => Self::FireResistance,
            13 => Self::LongFireResistance,
            14 => Self::Swiftness,
            15 => Self::LongSwiftness,
            16 => Self::StrongSwiftness,
            17 => Self::Slowness,
            18 => Self::LongSlowness,
            19 => Self::WaterBreathing,
            20 => Self::LongWaterBreathing,
            21 => Self::Healing,
            22 => Self::StrongHealing,
            23 => Self::Harming,
            24 => Self::StrongHarming,
            25 => Self::Poison,
            26 => Self::LongPoison,
            27 => Self::StrongPoison,
            28 => Self::Regeneration,
            29 => Self::LongRegeneration,
            30 => Self::StrongRegeneration,
            31 => Self::Strength,
            32 => Self::LongStrength,
            33 => Self::StrongStrength,
            34 => Self::Weakness,
            35 => Self::LongWeakness,
            36 => Self::Wither,
            37 => Self::TurtleMaster,
            38 => Self::LongTurtleMaster,
            39 => Self::StrongTurtleMaster,
            40 => Self::SlowFalling,
            41 => Self::LongSlowFalling,
            42 => Self::StrongSlowness,
            _ => Self::Custom(id),
        }
    }
}
