// Code generated by abi-gen v1. DO NOT EDIT.

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum EffectType {
    Speed = dragonfly_plugin_sys::DF_EFFECT_SPEED,
    Slowness = dragonfly_plugin_sys::DF_EFFECT_SLOWNESS,
    Haste = dragonfly_plugin_sys::DF_EFFECT_HASTE,
    MiningFatigue = dragonfly_plugin_sys::DF_EFFECT_MINING_FATIGUE,
    Strength = dragonfly_plugin_sys::DF_EFFECT_STRENGTH,
    InstantHealth = dragonfly_plugin_sys::DF_EFFECT_INSTANT_HEALTH,
    InstantDamage = dragonfly_plugin_sys::DF_EFFECT_INSTANT_DAMAGE,
    JumpBoost = dragonfly_plugin_sys::DF_EFFECT_JUMP_BOOST,
    Nausea = dragonfly_plugin_sys::DF_EFFECT_NAUSEA,
    Regeneration = dragonfly_plugin_sys::DF_EFFECT_REGENERATION,
    Resistance = dragonfly_plugin_sys::DF_EFFECT_RESISTANCE,
    FireResistance = dragonfly_plugin_sys::DF_EFFECT_FIRE_RESISTANCE,
    WaterBreathing = dragonfly_plugin_sys::DF_EFFECT_WATER_BREATHING,
    Invisibility = dragonfly_plugin_sys::DF_EFFECT_INVISIBILITY,
    Blindness = dragonfly_plugin_sys::DF_EFFECT_BLINDNESS,
    NightVision = dragonfly_plugin_sys::DF_EFFECT_NIGHT_VISION,
    Hunger = dragonfly_plugin_sys::DF_EFFECT_HUNGER,
    Weakness = dragonfly_plugin_sys::DF_EFFECT_WEAKNESS,
    Poison = dragonfly_plugin_sys::DF_EFFECT_POISON,
    Wither = dragonfly_plugin_sys::DF_EFFECT_WITHER,
    HealthBoost = dragonfly_plugin_sys::DF_EFFECT_HEALTH_BOOST,
    Absorption = dragonfly_plugin_sys::DF_EFFECT_ABSORPTION,
    Saturation = dragonfly_plugin_sys::DF_EFFECT_SATURATION,
    Levitation = dragonfly_plugin_sys::DF_EFFECT_LEVITATION,
    FatalPoison = dragonfly_plugin_sys::DF_EFFECT_FATAL_POISON,
    ConduitPower = dragonfly_plugin_sys::DF_EFFECT_CONDUIT_POWER,
    SlowFalling = dragonfly_plugin_sys::DF_EFFECT_SLOW_FALLING,
    Darkness = dragonfly_plugin_sys::DF_EFFECT_DARKNESS,
}

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Sound {
    AnvilBreak = dragonfly_plugin_sys::DF_SOUND_ANVIL_BREAK,
    AnvilLand = dragonfly_plugin_sys::DF_SOUND_ANVIL_LAND,
    AnvilUse = dragonfly_plugin_sys::DF_SOUND_ANVIL_USE,
    ArrowHit = dragonfly_plugin_sys::DF_SOUND_ARROW_HIT,
    BarrelClose = dragonfly_plugin_sys::DF_SOUND_BARREL_CLOSE,
    BarrelOpen = dragonfly_plugin_sys::DF_SOUND_BARREL_OPEN,
    BlastFurnaceCrackle = dragonfly_plugin_sys::DF_SOUND_BLAST_FURNACE_CRACKLE,
    BowShoot = dragonfly_plugin_sys::DF_SOUND_BOW_SHOOT,
    Burning = dragonfly_plugin_sys::DF_SOUND_BURNING,
    Burp = dragonfly_plugin_sys::DF_SOUND_BURP,
    CampfireCrackle = dragonfly_plugin_sys::DF_SOUND_CAMPFIRE_CRACKLE,
    ChestClose = dragonfly_plugin_sys::DF_SOUND_CHEST_CLOSE,
    ChestOpen = dragonfly_plugin_sys::DF_SOUND_CHEST_OPEN,
    Click = dragonfly_plugin_sys::DF_SOUND_CLICK,
    ComposterEmpty = dragonfly_plugin_sys::DF_SOUND_COMPOSTER_EMPTY,
    ComposterFill = dragonfly_plugin_sys::DF_SOUND_COMPOSTER_FILL,
    ComposterFillLayer = dragonfly_plugin_sys::DF_SOUND_COMPOSTER_FILL_LAYER,
    ComposterReady = dragonfly_plugin_sys::DF_SOUND_COMPOSTER_READY,
    CopperScraped = dragonfly_plugin_sys::DF_SOUND_COPPER_SCRAPED,
    CrossbowShoot = dragonfly_plugin_sys::DF_SOUND_CROSSBOW_SHOOT,
    DecoratedPotInsertFailed = dragonfly_plugin_sys::DF_SOUND_DECORATED_POT_INSERT_FAILED,
    Deny = dragonfly_plugin_sys::DF_SOUND_DENY,
    DoorCrash = dragonfly_plugin_sys::DF_SOUND_DOOR_CRASH,
    Drowning = dragonfly_plugin_sys::DF_SOUND_DROWNING,
    EnderChestClose = dragonfly_plugin_sys::DF_SOUND_ENDER_CHEST_CLOSE,
    EnderChestOpen = dragonfly_plugin_sys::DF_SOUND_ENDER_CHEST_OPEN,
    Experience = dragonfly_plugin_sys::DF_SOUND_EXPERIENCE,
    Explosion = dragonfly_plugin_sys::DF_SOUND_EXPLOSION,
    FireCharge = dragonfly_plugin_sys::DF_SOUND_FIRE_CHARGE,
    FireExtinguish = dragonfly_plugin_sys::DF_SOUND_FIRE_EXTINGUISH,
    FireworkBlast = dragonfly_plugin_sys::DF_SOUND_FIREWORK_BLAST,
    FireworkHugeBlast = dragonfly_plugin_sys::DF_SOUND_FIREWORK_HUGE_BLAST,
    FireworkLaunch = dragonfly_plugin_sys::DF_SOUND_FIREWORK_LAUNCH,
    FireworkTwinkle = dragonfly_plugin_sys::DF_SOUND_FIREWORK_TWINKLE,
    Fizz = dragonfly_plugin_sys::DF_SOUND_FIZZ,
    FurnaceCrackle = dragonfly_plugin_sys::DF_SOUND_FURNACE_CRACKLE,
    GhastShoot = dragonfly_plugin_sys::DF_SOUND_GHAST_SHOOT,
    GhastWarning = dragonfly_plugin_sys::DF_SOUND_GHAST_WARNING,
    GlassBreak = dragonfly_plugin_sys::DF_SOUND_GLASS_BREAK,
    Ignite = dragonfly_plugin_sys::DF_SOUND_IGNITE,
    ItemAdd = dragonfly_plugin_sys::DF_SOUND_ITEM_ADD,
    ItemBreak = dragonfly_plugin_sys::DF_SOUND_ITEM_BREAK,
    ItemFrameRemove = dragonfly_plugin_sys::DF_SOUND_ITEM_FRAME_REMOVE,
    ItemFrameRotate = dragonfly_plugin_sys::DF_SOUND_ITEM_FRAME_ROTATE,
    ItemThrow = dragonfly_plugin_sys::DF_SOUND_ITEM_THROW,
    LecternBookPlace = dragonfly_plugin_sys::DF_SOUND_LECTERN_BOOK_PLACE,
    LevelUp = dragonfly_plugin_sys::DF_SOUND_LEVEL_UP,
    LightningExplode = dragonfly_plugin_sys::DF_SOUND_LIGHTNING_EXPLODE,
    LightningThunder = dragonfly_plugin_sys::DF_SOUND_LIGHTNING_THUNDER,
    MusicDiscEnd = dragonfly_plugin_sys::DF_SOUND_MUSIC_DISC_END,
    Pop = dragonfly_plugin_sys::DF_SOUND_POP,
    PotionBrewed = dragonfly_plugin_sys::DF_SOUND_POTION_BREWED,
    PowerOff = dragonfly_plugin_sys::DF_SOUND_POWER_OFF,
    PowerOn = dragonfly_plugin_sys::DF_SOUND_POWER_ON,
    SignWaxed = dragonfly_plugin_sys::DF_SOUND_SIGN_WAXED,
    SmokerCrackle = dragonfly_plugin_sys::DF_SOUND_SMOKER_CRACKLE,
    StopUsingSpyglass = dragonfly_plugin_sys::DF_SOUND_STOP_USING_SPYGLASS,
    Tnt = dragonfly_plugin_sys::DF_SOUND_TNT,
    Teleport = dragonfly_plugin_sys::DF_SOUND_TELEPORT,
    Thunder = dragonfly_plugin_sys::DF_SOUND_THUNDER,
    Totem = dragonfly_plugin_sys::DF_SOUND_TOTEM,
    UseSpyglass = dragonfly_plugin_sys::DF_SOUND_USE_SPYGLASS,
    WaxRemoved = dragonfly_plugin_sys::DF_SOUND_WAX_REMOVED,
    WaxedSignFailedInteraction = dragonfly_plugin_sys::DF_SOUND_WAXED_SIGN_FAILED_INTERACTION,
}

impl Player {
    pub fn message(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_MESSAGE, value); }
    pub fn send_tip(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_TIP, value); }
    pub fn send_popup(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_POPUP, value); }
    pub fn send_jukebox_popup(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_JUKEBOX_POPUP, value); }
    pub fn set_name_tag(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_NAME_TAG, value); }
    pub fn disconnect(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_DISCONNECT, value); }
    pub fn kick(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_KICK, value); }
    pub fn set_game_mode(&self, value: GameMode) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_GAME_MODE, 0.0, value as i64); }
    pub fn game_mode(&self) -> GameMode { match self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_GAME_MODE).integer { 1 => GameMode::Creative, 2 => GameMode::Adventure, 3 => GameMode::Spectator, _ => GameMode::Survival } }
    pub fn heal(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_HEAL, value, 0); }
    pub fn hurt(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_HURT, value, 0); }
    pub fn set_food(&self, value: i32) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_FOOD, 0.0, i64::from(value)); }
    pub fn food(&self) -> i32 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_FOOD).integer as i32 }
    pub fn set_max_health(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_MAX_HEALTH, value, 0); }
    pub fn max_health(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_MAX_HEALTH).number }
    pub fn health(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_HEALTH).number }
    pub fn set_experience_level(&self, value: i32) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_LEVEL, 0.0, i64::from(value)); }
    pub fn experience_level(&self) -> i32 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_LEVEL).integer as i32 }
    pub fn set_experience_progress(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_PROGRESS, value, 0); }
    pub fn experience_progress(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_PROGRESS).number }
    pub fn set_scale(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_SCALE, value, 0); }
    pub fn scale(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_SCALE).number }
    pub fn set_invisible(&self, value: bool) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_INVISIBLE, 0.0, value as i64); }
    pub fn invisible(&self) -> bool { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_INVISIBLE).integer != 0 }
    pub fn set_immobile(&self, value: bool) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_IMMOBILE, 0.0, value as i64); }
    pub fn immobile(&self) -> bool { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_IMMOBILE).integer != 0 }
    pub fn play_sound(&self, value: Sound) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_SOUND, 0.0, value as i64); }
}
