// Code generated by abi-gen v1. DO NOT EDIT.

#[repr(u32)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum EffectType {
    Speed = dragonfly_plugin_sys::DF_EFFECT_SPEED,
    Slowness = dragonfly_plugin_sys::DF_EFFECT_SLOWNESS,
    Haste = dragonfly_plugin_sys::DF_EFFECT_HASTE,
    MiningFatigue = dragonfly_plugin_sys::DF_EFFECT_MINING_FATIGUE,
    Strength = dragonfly_plugin_sys::DF_EFFECT_STRENGTH,
    InstantHealth = dragonfly_plugin_sys::DF_EFFECT_INSTANT_HEALTH,
    InstantDamage = dragonfly_plugin_sys::DF_EFFECT_INSTANT_DAMAGE,
    JumpBoost = dragonfly_plugin_sys::DF_EFFECT_JUMP_BOOST,
    Nausea = dragonfly_plugin_sys::DF_EFFECT_NAUSEA,
    Regeneration = dragonfly_plugin_sys::DF_EFFECT_REGENERATION,
    Resistance = dragonfly_plugin_sys::DF_EFFECT_RESISTANCE,
    FireResistance = dragonfly_plugin_sys::DF_EFFECT_FIRE_RESISTANCE,
    WaterBreathing = dragonfly_plugin_sys::DF_EFFECT_WATER_BREATHING,
    Invisibility = dragonfly_plugin_sys::DF_EFFECT_INVISIBILITY,
    Blindness = dragonfly_plugin_sys::DF_EFFECT_BLINDNESS,
    NightVision = dragonfly_plugin_sys::DF_EFFECT_NIGHT_VISION,
    Hunger = dragonfly_plugin_sys::DF_EFFECT_HUNGER,
    Weakness = dragonfly_plugin_sys::DF_EFFECT_WEAKNESS,
    Poison = dragonfly_plugin_sys::DF_EFFECT_POISON,
    Wither = dragonfly_plugin_sys::DF_EFFECT_WITHER,
    HealthBoost = dragonfly_plugin_sys::DF_EFFECT_HEALTH_BOOST,
    Absorption = dragonfly_plugin_sys::DF_EFFECT_ABSORPTION,
    Saturation = dragonfly_plugin_sys::DF_EFFECT_SATURATION,
    Levitation = dragonfly_plugin_sys::DF_EFFECT_LEVITATION,
    FatalPoison = dragonfly_plugin_sys::DF_EFFECT_FATAL_POISON,
    ConduitPower = dragonfly_plugin_sys::DF_EFFECT_CONDUIT_POWER,
    SlowFalling = dragonfly_plugin_sys::DF_EFFECT_SLOW_FALLING,
    Darkness = dragonfly_plugin_sys::DF_EFFECT_DARKNESS,
}

impl Player {
    pub fn message(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_MESSAGE, value); }
    pub fn send_tip(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_TIP, value); }
    pub fn send_popup(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_POPUP, value); }
    pub fn send_jukebox_popup(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_JUKEBOX_POPUP, value); }
    pub fn set_name_tag(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_NAME_TAG, value); }
    pub fn set_game_mode(&self, value: GameMode) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_GAME_MODE, 0.0, value as i64); }
    pub fn game_mode(&self) -> GameMode { match self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_GAME_MODE).integer { 1 => GameMode::Creative, 2 => GameMode::Adventure, 3 => GameMode::Spectator, _ => GameMode::Survival } }
    pub fn heal(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_HEAL, value, 0); }
    pub fn hurt(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_HURT, value, 0); }
    pub fn set_food(&self, value: i32) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_FOOD, 0.0, i64::from(value)); }
    pub fn food(&self) -> i32 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_FOOD).integer as i32 }
    pub fn set_max_health(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_MAX_HEALTH, value, 0); }
    pub fn max_health(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_MAX_HEALTH).number }
    pub fn health(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_HEALTH).number }
    pub fn set_experience_level(&self, value: i32) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_LEVEL, 0.0, i64::from(value)); }
    pub fn experience_level(&self) -> i32 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_LEVEL).integer as i32 }
    pub fn set_experience_progress(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_PROGRESS, value, 0); }
    pub fn experience_progress(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_PROGRESS).number }
    pub fn set_scale(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_SCALE, value, 0); }
    pub fn scale(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_SCALE).number }
    pub fn set_invisible(&self, value: bool) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_INVISIBLE, 0.0, value as i64); }
    pub fn invisible(&self) -> bool { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_INVISIBLE).integer != 0 }
    pub fn set_immobile(&self, value: bool) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_IMMOBILE, 0.0, value as i64); }
    pub fn immobile(&self) -> bool { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_IMMOBILE).integer != 0 }
}
