using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Dragonfly.Generator;

[Generator]
public sealed class PluginEntryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var plugins = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (syntax, _) => PluginType(syntax))
            .Where(static plugin => plugin.HasValue)
            .Select(static (plugin, _) => plugin!.Value);

        var reflectedCommandTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                static (syntax, _) => ReflectedCommandType(syntax))
            .Where(static type => type.HasValue)
            .Select(static (type, _) => type!.Value);

        var reflectedFormTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax { BaseList: not null },
                static (syntax, _) => ReflectedFormType(syntax))
            .Where(static type => type.HasValue)
            .Select(static (type, _) => type!.Value);

        context.RegisterSourceOutput(
            plugins.Collect().Combine(reflectedCommandTypes.Collect()).Combine(reflectedFormTypes.Collect()),
            static (output, values) =>
        {
            if (values.Left.Left.Length == 0) return;
            var plugin = values.Left.Left[0];
            var commandDependencies = values.Left.Right
                .SelectMany(static type => type.Types)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static type => type, StringComparer.Ordinal)
                .Select(static type => $$"""
                    [global::System.Diagnostics.CodeAnalysis.DynamicDependency(
                        global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields |
                        global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors,
                        typeof({{type}}))]
                    """);
            var formDependencies = values.Right
                .SelectMany(static type => type.Types)
                .Distinct()
                .OrderBy(static type => type.TypeName, StringComparer.Ordinal)
                .ThenBy(static type => type.AssemblyName, StringComparer.Ordinal)
                .Select(static type => $$"""
                    [global::System.Diagnostics.CodeAnalysis.DynamicDependency(
                        global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicFields |
                        global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicConstructors |
                        global::System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes.PublicMethods,
                        {{SymbolDisplay.FormatLiteral(type.TypeName, true)}},
                        {{SymbolDisplay.FormatLiteral(type.AssemblyName, true)}})]
                    """);
            var dependencies = string.Join("\n", commandDependencies.Concat(formDependencies));
            output.AddSource("DragonflyPluginEntry.g.cs", $$"""
                // <auto-generated />
                namespace Dragonfly.Generated;

                internal static unsafe class PluginEntry
                {
                {{dependencies}}
                    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(
                        EntryPoint = "df_plugin_entry_v8",
                        CallConvs = [typeof(global::System.Runtime.CompilerServices.CallConvCdecl)])]
                    public static global::Dragonfly.Native.PluginApi* Load() =>
                        global::Dragonfly.PluginExport<{{plugin.Type}}>.Api({{plugin.Subscriptions}}UL);
                }
                """);
        });
    }

    private static ReflectedMetadataTypeInfo? ReflectedFormType(GeneratorSyntaxContext context)
    {
        var declaration = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type ||
            type.IsAbstract || type.TypeKind is not (TypeKind.Class or TypeKind.Struct)) return null;
        if (!type.AllInterfaces.Any(static implemented => implemented.ToDisplayString() is
                "Dragonfly.Form.Submittable" or
                "Dragonfly.Form.MenuSubmittable" or
                "Dragonfly.Form.ModalSubmittable")) return null;
        return new ReflectedMetadataTypeInfo([
            new ReflectedMetadataType(MetadataName(type), type.ContainingAssembly.Identity.Name)
        ]);
    }

    private static string MetadataName(INamedTypeSymbol type)
    {
        if (type.ContainingType is not null) return MetadataName(type.ContainingType) + "." + type.MetadataName;
        if (type.ContainingNamespace.IsGlobalNamespace) return type.MetadataName;
        return type.ContainingNamespace.ToDisplayString() + "." + type.MetadataName;
    }

    private static ReflectedTypeInfo? ReflectedCommandType(GeneratorSyntaxContext context)
    {
        var declaration = (TypeDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type ||
            type.IsAbstract ||
            type.TypeKind is not (TypeKind.Class or TypeKind.Struct)) return null;

        if (!type.AllInterfaces.Any(static implemented =>
                implemented.ToDisplayString() is "Dragonfly.Cmd.Runnable" or "Dragonfly.Cmd.Enum")) return null;

        var reflected = new List<string> { type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat) };
        reflected.AddRange(type.GetMembers().OfType<IFieldSymbol>()
            .Where(static field => !field.IsStatic && field.DeclaredAccessibility == Accessibility.Public)
            .Where(static field => field.Type.TypeKind == TypeKind.Enum ||
                field.Type is INamedTypeSymbol named && named.OriginalDefinition.ToDisplayString() == "Dragonfly.Cmd.Optional<T>")
            .Select(static field => field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
        return new ReflectedTypeInfo(reflected.ToArray());
    }

    private static PluginInfo? PluginType(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type || type.IsAbstract)
            return null;
        for (var current = type.BaseType; current is not null; current = current.BaseType)
            if (current.ToDisplayString() == "Dragonfly.Plugin")
            {
                ulong subscriptions = 0;
                foreach (var method in type.GetMembers().OfType<IMethodSymbol>())
                {
                    if (!method.IsOverride) continue;
                    foreach (var attribute in method.OverriddenMethod?.GetAttributes() ?? [])
                    {
                        if (attribute.AttributeClass?.ToDisplayString() != "Dragonfly.HandlerSubscriptionAttribute" ||
                            attribute.ConstructorArguments.Length != 1 ||
                            attribute.ConstructorArguments[0].Value is not ulong value) continue;
                        subscriptions |= value;
                    }
                }
                return new PluginInfo(
                    type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    subscriptions);
            }
        return null;
    }

    private readonly struct PluginInfo(string type, ulong subscriptions)
    {
        public string Type { get; } = type;
        public ulong Subscriptions { get; } = subscriptions;
    }
    private readonly struct ReflectedTypeInfo(string[] types)
    {
        public string[] Types { get; } = types;
    }
    private readonly struct ReflectedMetadataType(string typeName, string assemblyName)
    {
        public string TypeName { get; } = typeName;
        public string AssemblyName { get; } = assemblyName;
    }
    private readonly struct ReflectedMetadataTypeInfo(ReflectedMetadataType[] types)
    {
        public ReflectedMetadataType[] Types { get; } = types;
    }
}
