// Code generated by abi-gen v1. DO NOT EDIT.

package host

import (
	"math"

	"github.com/bedrock-gophers/plugins/internal/native"
	"github.com/df-mc/dragonfly/server/player"
	"github.com/df-mc/dragonfly/server/world"
	dfsound "github.com/df-mc/dragonfly/server/world/sound"
)

func sendPlayerText(connected *player.Player, kind native.PlayerTextKind, message string) bool {
	switch kind {
	case native.PlayerTextMessage:
		connected.Message(message)
	case native.PlayerTextTip:
		connected.SendTip(message)
	case native.PlayerTextPopup:
		connected.SendPopup(message)
	case native.PlayerTextJukeboxPopup:
		connected.SendJukeboxPopup(message)
	case native.PlayerTextNameTag:
		connected.SetNameTag(message)
	case native.PlayerTextDisconnect:
		connected.Disconnect(message)
	case native.PlayerTextKick:
		connected.Disconnect(message)
	default:
		return false
	}
	return true
}

func playerSound(kind native.SoundType) (world.Sound, bool) {
	switch kind {
	case native.SoundAnvilBreak:
		return dfsound.AnvilBreak{}, true
	case native.SoundAnvilLand:
		return dfsound.AnvilLand{}, true
	case native.SoundAnvilUse:
		return dfsound.AnvilUse{}, true
	case native.SoundArrowHit:
		return dfsound.ArrowHit{}, true
	case native.SoundBarrelClose:
		return dfsound.BarrelClose{}, true
	case native.SoundBarrelOpen:
		return dfsound.BarrelOpen{}, true
	case native.SoundBlastFurnaceCrackle:
		return dfsound.BlastFurnaceCrackle{}, true
	case native.SoundBowShoot:
		return dfsound.BowShoot{}, true
	case native.SoundBurning:
		return dfsound.Burning{}, true
	case native.SoundBurp:
		return dfsound.Burp{}, true
	case native.SoundCampfireCrackle:
		return dfsound.CampfireCrackle{}, true
	case native.SoundChestClose:
		return dfsound.ChestClose{}, true
	case native.SoundChestOpen:
		return dfsound.ChestOpen{}, true
	case native.SoundClick:
		return dfsound.Click{}, true
	case native.SoundComposterEmpty:
		return dfsound.ComposterEmpty{}, true
	case native.SoundComposterFill:
		return dfsound.ComposterFill{}, true
	case native.SoundComposterFillLayer:
		return dfsound.ComposterFillLayer{}, true
	case native.SoundComposterReady:
		return dfsound.ComposterReady{}, true
	case native.SoundCopperScraped:
		return dfsound.CopperScraped{}, true
	case native.SoundCrossbowShoot:
		return dfsound.CrossbowShoot{}, true
	case native.SoundDecoratedPotInsertFailed:
		return dfsound.DecoratedPotInsertFailed{}, true
	case native.SoundDeny:
		return dfsound.Deny{}, true
	case native.SoundDoorCrash:
		return dfsound.DoorCrash{}, true
	case native.SoundDrowning:
		return dfsound.Drowning{}, true
	case native.SoundEnderChestClose:
		return dfsound.EnderChestClose{}, true
	case native.SoundEnderChestOpen:
		return dfsound.EnderChestOpen{}, true
	case native.SoundExperience:
		return dfsound.Experience{}, true
	case native.SoundExplosion:
		return dfsound.Explosion{}, true
	case native.SoundFireCharge:
		return dfsound.FireCharge{}, true
	case native.SoundFireExtinguish:
		return dfsound.FireExtinguish{}, true
	case native.SoundFireworkBlast:
		return dfsound.FireworkBlast{}, true
	case native.SoundFireworkHugeBlast:
		return dfsound.FireworkHugeBlast{}, true
	case native.SoundFireworkLaunch:
		return dfsound.FireworkLaunch{}, true
	case native.SoundFireworkTwinkle:
		return dfsound.FireworkTwinkle{}, true
	case native.SoundFizz:
		return dfsound.Fizz{}, true
	case native.SoundFurnaceCrackle:
		return dfsound.FurnaceCrackle{}, true
	case native.SoundGhastShoot:
		return dfsound.GhastShoot{}, true
	case native.SoundGhastWarning:
		return dfsound.GhastWarning{}, true
	case native.SoundGlassBreak:
		return dfsound.GlassBreak{}, true
	case native.SoundIgnite:
		return dfsound.Ignite{}, true
	case native.SoundItemAdd:
		return dfsound.ItemAdd{}, true
	case native.SoundItemBreak:
		return dfsound.ItemBreak{}, true
	case native.SoundItemFrameRemove:
		return dfsound.ItemFrameRemove{}, true
	case native.SoundItemFrameRotate:
		return dfsound.ItemFrameRotate{}, true
	case native.SoundItemThrow:
		return dfsound.ItemThrow{}, true
	case native.SoundLecternBookPlace:
		return dfsound.LecternBookPlace{}, true
	case native.SoundLevelUp:
		return dfsound.LevelUp{}, true
	case native.SoundLightningExplode:
		return dfsound.LightningExplode{}, true
	case native.SoundLightningThunder:
		return dfsound.LightningThunder{}, true
	case native.SoundMusicDiscEnd:
		return dfsound.MusicDiscEnd{}, true
	case native.SoundPop:
		return dfsound.Pop{}, true
	case native.SoundPotionBrewed:
		return dfsound.PotionBrewed{}, true
	case native.SoundPowerOff:
		return dfsound.PowerOff{}, true
	case native.SoundPowerOn:
		return dfsound.PowerOn{}, true
	case native.SoundSignWaxed:
		return dfsound.SignWaxed{}, true
	case native.SoundSmokerCrackle:
		return dfsound.SmokerCrackle{}, true
	case native.SoundStopUsingSpyglass:
		return dfsound.StopUsingSpyglass{}, true
	case native.SoundTnt:
		return dfsound.TNT{}, true
	case native.SoundTeleport:
		return dfsound.Teleport{}, true
	case native.SoundThunder:
		return dfsound.Thunder{}, true
	case native.SoundTotem:
		return dfsound.Totem{}, true
	case native.SoundUseSpyglass:
		return dfsound.UseSpyglass{}, true
	case native.SoundWaxRemoved:
		return dfsound.WaxRemoved{}, true
	case native.SoundWaxedSignFailedInteraction:
		return dfsound.WaxedSignFailedInteraction{}, true
	default:
		return nil, false
	}
}

func setPlayerState(connected *player.Player, kind native.PlayerStateKind, value native.PlayerStateValue) bool {
	switch kind {
	case native.PlayerStateGameMode:
		mode, ok := world.GameModeByID(int(value.Integer))
		if !ok {
			return false
		}
		connected.SetGameMode(mode)
	case native.PlayerStateHeal:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) || value.Number < 0 {
			return false
		}
		connected.Heal(value.Number, pluginHealingSource{})
	case native.PlayerStateHurt:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) || value.Number < 0 {
			return false
		}
		connected.Hurt(value.Number, pluginDamageSource{})
	case native.PlayerStateFood:
		if value.Integer < math.MinInt32 || value.Integer > math.MaxInt32 {
			return false
		}
		connected.SetFood(int(value.Integer))
	case native.PlayerStateMaxHealth:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) || value.Number <= 0 {
			return false
		}
		connected.SetMaxHealth(value.Number)
	case native.PlayerStateExperienceLevel:
		if value.Integer < math.MinInt32 || value.Integer > math.MaxInt32 || value.Integer < 0 {
			return false
		}
		connected.SetExperienceLevel(int(value.Integer))
	case native.PlayerStateExperienceProgress:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) || value.Number < 0 || value.Number > 1 {
			return false
		}
		connected.SetExperienceProgress(value.Number)
	case native.PlayerStateScale:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) {
			return false
		}
		connected.SetScale(value.Number)
	case native.PlayerStateInvisible:
		if value.Integer != 0 && value.Integer != 1 {
			return false
		}
		if value.Integer != 0 {
			connected.SetInvisible()
		} else {
			connected.SetVisible()
		}
	case native.PlayerStateImmobile:
		if value.Integer != 0 && value.Integer != 1 {
			return false
		}
		if value.Integer != 0 {
			connected.SetImmobile()
		} else {
			connected.SetMobile()
		}
	case native.PlayerStateSound:
		sound, ok := playerSound(native.SoundType(value.Integer))
		if !ok {
			return false
		}
		connected.PlaySound(sound)
	default:
		return false
	}
	return true
}

func readPlayerState(connected *player.Player, kind native.PlayerStateKind) (native.PlayerStateValue, bool) {
	switch kind {
	case native.PlayerStateGameMode:
		value, ok := world.GameModeID(connected.GameMode())
		return native.PlayerStateValue{Integer: int64(value)}, ok
	case native.PlayerStateFood:
		return native.PlayerStateValue{Integer: int64(connected.Food())}, true
	case native.PlayerStateMaxHealth:
		return native.PlayerStateValue{Number: connected.MaxHealth()}, true
	case native.PlayerStateHealth:
		return native.PlayerStateValue{Number: connected.Health()}, true
	case native.PlayerStateExperienceLevel:
		return native.PlayerStateValue{Integer: int64(connected.ExperienceLevel())}, true
	case native.PlayerStateExperienceProgress:
		return native.PlayerStateValue{Number: connected.ExperienceProgress()}, true
	case native.PlayerStateScale:
		return native.PlayerStateValue{Number: connected.Scale()}, true
	case native.PlayerStateInvisible:
		if connected.Invisible() {
			return native.PlayerStateValue{Integer: 1}, true
		}
		return native.PlayerStateValue{}, true
	case native.PlayerStateImmobile:
		if connected.Immobile() {
			return native.PlayerStateValue{Integer: 1}, true
		}
		return native.PlayerStateValue{}, true
	default:
		return native.PlayerStateValue{}, false
	}
}
